### ISSUE TITLE
Release 3.0.0-M1

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#10124]
- [x] Move open issues from the current to the next milestone
- [x] Tag the release
- [x] Update `baseVersion` to the next release's version
- [ ] Update `scalaVersion` (and, if applicable, the `sbt-dotty` version) in the Dotty ecosystem projects
  - [x] https://github.com/lampepfl/dotty-example-project [![Build Status](https://travis-ci.org/lampepfl/dotty-example-project.svg?branch=master)](https://travis-ci.org/lampepfl/dotty-example-project)
  - [x] https://github.com/lampepfl/dotty-example-project/tree/mill
  - [x] https://github.com/lampepfl/dotty.g8 [![Build Status](https://travis-ci.org/lampepfl/dotty.g8.svg?branch=master)](https://travis-ci.org/lampepfl/dotty.g8/)
  - [x] https://github.com/lampepfl/dotty-cross.g8 [![Build Status](https://travis-ci.org/lampepfl/dotty-cross.g8.svg?branch=master)](https://travis-ci.org/lampepfl/dotty-cross.g8/)
  - [x] https://github.com/lampepfl/dotty-staging.g8 [![Build Status](https://travis-ci.org/lampepfl/dotty-staging.g8.svg?branch=master)](https://travis-ci.org/lampepfl/dotty-staging.g8)
  - [x] https://github.com/lampepfl/homebrew-brew [![Build Status](https://travis-ci.org/lampepfl/homebrew-brew.svg?branch=master)](https://travis-ci.org/lampepfl/homebrew-brew)
  - [x] https://github.com/lampepfl/packtest [![Build Status](https://travis-ci.org/lampepfl/packtest.svg?branch=master)](https://travis-ci.org/lampepfl/packtest)
  - [x] https://github.com/lampepfl/xml-interpolator [![Build Status](https://travis-ci.org/lampepfl/xml-interpolator.svg?branch=master)](https://travis-ci.org/lampepfl/xml-interpolator)
  - [x] https://github.com/scalacenter/scastie
  - [x] Dotty reference compiler [![Build Status](http://dotty-ci.epfl.ch/api/badges/lampepfl/dotty/status.svg)](http://dotty-ci.epfl.ch/lampepfl/dotty)
  - [ ] Scalac [![Build Status](https://travis-ci.org/scala/scala.svg?branch=2.13.x)](https://travis-ci.org/scala/scala)
- [x] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Publish Blog Post on dotty.epfl.ch
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

**Comment by smarter** [comment]
Publishing failed: https://github.com/lampepfl/dotty/runs/1333773977?check_suite_focus=true

> sha256sum: 'dist/target/dotty-*': No such file or directory

**Comment by smarter** [comment]
>  Update scalaVersion (and, if applicable, the sbt-dotty version) in the Dotty ecosystem projects 
> - [ ] Scalac

It looks like this was forgotten, I'm looking into it now but we really should make sure we keep Scala 2 always using the latest Dotty otherwise regressions might appear and go unnoticed for a long time.

**Comment by smarter** [comment]
https://github.com/scala/scala/pull/9345
