### ISSUE TITLE
Cleanup our list of compiler flags

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#10236]
We should go through https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/config/ScalaSettings.scala and clean it up, in particular there's a bunch of flags which don't do anything (because they were never implemented or because they were dropped) which should just be removed, there's flags which try to do something but never worked (`-Xno-value-classes`) and there are flags which don't separate words by hyphens (`-noindent`). It might also be worth reclassifying some flags (if `-Ysemanticdb` is officially supported it should be `-Xsemanticdb` or `-semanticdb`)

**Comment by smarter** [comment]
`-explain-types` prints compiler implementation details about constraint solving, it should be a `-Y` flag I think

**Comment by som-snytt** [comment]
It's almost the weekend, although it's hard to tell; I'll PR this, with an interest in introducing `-Wconf` and also aligning with 2.13 `-VWXY` scheme. I don't know if I can trust polling numbers, but I wonder if settings should retain aliases such as `-Xprint` for `-Vprint`. (Aliases encourage recidivism.) The advantage of the scheme is that -V means more verbosity without changing behavior (modulo forcing types), similarly -W for warnings. Then -XY are about behaviors.

**Comment by anatoliykmetyuk** [comment]
TODO:
- Align as much as possible w/2.13

**Comment by sjrd** [comment]
I just submitted a first batch at #10655. In addition, here are some more thoughts:

* Make `-priorityclasspath` a `-Y` option?
* Remove `-Xignore-scala2-macros`?
* Get rid of `-Yemit-tasty-in-class` and the handling of `.hasTasty` files?
* Get rid of `-Yno-inline`? It's used by the doc tool, but disabling inlining can change inferred result types and otherwise produce a different language. We shouldn't do that.

**Comment by smarter** [comment]
> Make -priorityclasspath a -Y option?

I think we should try to remove it, I'm not sure it actually does anything in the one test where it's used right now.

> Remove -Xignore-scala2-macros?

That's still useful for making progress when trying to port code.

> Get rid of -Yemit-tasty-in-class and the handling of .hasTasty files?

Yes it's not maintained so might be broken anyway.

> Get rid of -Yno-inline?

Wow. Yes, definitely :). It's the same level of cannot-possibly-work as `-Xno-value-classes`

**Comment by sjrd** [comment]
Status update: everything is done, except

* [ ] #10733 Rename the setting -noindent into -no-indent. (blocked by a failure in community build that I can't make sense of)
* [ ] #10736 Remove the -priorityclasspath setting. (ready for review, blocked by the flaky `Idempotency` test failure for full validation)
* [ ] #10737 Make -explain-types a -Y option as -Yexplain-types. (ready for review)
* [ ] Support new `-V` options of Scala 2.13 (which are alias as old `-X` options that we do support)

I don't think the last item is critical for M3 or even for the final release. Those options should be renamed while keeping the old aliases anyway, so we won't break anything if we do it later. Therefore, I am not going to work on this, as I believe my time is better used elsewhere at the moment.

@som-snytt You expressed interest in making those ports at some point. Are you still interested?

**Comment by som-snytt** [comment]
I mentioned that I will take another swing but don't want to block anyone if there is urgency. I'm operating at pandemic productivity levels. 

I agree with your comments about priorities. I don't have opinions on Scala 3-specific options yet.

https://github.com/lampepfl/dotty/issues/8908#issuecomment-737718183
