### ISSUE TITLE
Release 3.0.0-M2

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#10475]
- [x] Finalize the the stable and RC releases
  - [x] Look at the milestone of the RC version being released. Move all the open issues from it to the next milestone.
  - [x] Merge branch `0.M2.x` into `master` to guarantee that all of the `0.M2.x` commits are propagated to `master`
- [ ] Publish artifacts to Maven via CI
  - [ ] Create branch `M2`, set `baseVersion` to M2 there, and tag release
  - [x] On `master`, set `baseVersion` to `RC1`
- [ ] Update `scalaVersion` (and, if applicable, the `sbt-dotty` version) in the Dotty ecosystem projects
  - [ ] https://github.com/lampepfl/dotty-example-project [![Build Status](https://travis-ci.org/lampepfl/dotty-example-project.svg?branch=master)](https://travis-ci.org/lampepfl/dotty-example-project)
    - [ ] Committed to `master`
  - [ ] https://github.com/lampepfl/dotty-example-project/tree/mill
  - [ ] https://github.com/lampepfl/dotty.g8 [![Build Status](https://travis-ci.org/lampepfl/dotty.g8.svg?branch=master)](https://travis-ci.org/lampepfl/dotty.g8/)
    - [ ] Committed to `master`
  - [ ] https://github.com/lampepfl/dotty-cross.g8 [![Build Status](https://travis-ci.org/lampepfl/dotty-cross.g8.svg?branch=master)](https://travis-ci.org/lampepfl/dotty-cross.g8/)
    - [ ] Committed to `master`
  - [ ] https://github.com/lampepfl/dotty-staging.g8 [![Build Status](https://travis-ci.org/lampepfl/dotty-staging.g8.svg?branch=master)](https://travis-ci.org/lampepfl/dotty-staging.g8)
    - [ ] Committed to `master`
  - [ ] https://github.com/lampepfl/homebrew-brew [![Build Status](https://travis-ci.org/lampepfl/homebrew-brew.svg?branch=master)](https://travis-ci.org/lampepfl/homebrew-brew)
    - [ ] Committed to `master`
    - SHA256 sum for the artifact: `wget -q -O- https://github.com/lampepfl/dotty/releases/download/0.1.0-RC1/sha256sum.txt | grep ".tar.gz"`
  - [ ] https://github.com/lampepfl/packtest [![Build Status](https://travis-ci.org/lampepfl/packtest.svg?branch=master)](https://travis-ci.org/lampepfl/packtest)
    - [ ] Committed to `master`
  - [ ] https://github.com/lampepfl/xml-interpolator [![Build Status](https://travis-ci.org/lampepfl/xml-interpolator.svg?branch=master)](https://travis-ci.org/lampepfl/xml-interpolator)
    - [ ] PR submitted
    - [ ] PR merged
  - [ ] https://github.com/scalacenter/scastie
    - [ ] PR submitted
    - [ ] PR merged
    - [ ] https://scastie.scala-lang.org/ -> Build Settings -> Dotty mentions `0.1.0-RC1`
  - [ ] Dotty reference compiler [![Build Status](http://dotty-ci.epfl.ch/api/badges/lampepfl/dotty/status.svg)](http://dotty-ci.epfl.ch/lampepfl/dotty)
    - [ ] PR submitted
    - [ ] PR merged
  - [ ] Scalac [![Build Status](https://travis-ci.org/scala/scala.svg?branch=2.13.x)](https://travis-ci.org/scala/scala)
    - [ ] PR submitted
    - [ ] PR merged
- [ ] Announce the release
  - [ ] Publish releases for the RC and stable versions on GitHub Releases
  - [ ] Publish Blog Post on dotty.epfl.ch
  - [ ] Make an announcement thread on https://contributors.scala-lang.org
  - [ ] Tweet the announcement blog post on https://twitter.com/scala_lang

[Instructions on how to release](https://dotty.epfl.ch/docs/contributing/release.html)

**Comment by abgruszecki** [comment]
Should we close this?
