### ISSUE TITLE
Quoted reflection missing features list

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10619]
- [x] `Flags` (PR #10622)
  - [x] Add `Deferred`, `Infix`, `JavaStatic`, `Method`, `NoInit` and `Transparent`
  - [x] Remove `ModuleClass`
  - [x] Rename `Object` to `Module`
- [ ] `SymbolMethods`
  - [ ] ~Add `enclosingClass` and  `enclosingMethod`? (look in SourceCode)~
  - [x] Change signature to `def pos: Option[Position]` (PR #10656)
  - [x] Add `def hasAnnotation(sym: Symbol): Boolean` and `def getAnnotation(sym: Symbol): Option[Term]` (PR #10643)
  - [x] Rename `classMethod` to `declaredMethod` (PR #10645)
  - [x] Rename `typeMembers` to `memberTypes` (PR #10645)
  - [x] Rename `members` to `declarations` (PR #10645)
  - [x] Rename `method` to `memberMethod` (PR #10645)
  - [x] Add `declaredType` and `declaredTypes` (PR #10645)
- [x] Add `NameTyped` as super type of `TermRef` and `TypeRef` (PR #10630)
- [x] Add `AndOrType` as super type of `AndType` and `OrType` (PR #10630)
- [x] Add `MethodOrPoly` as super type of `MethodType` and `PolyType` (PR #10630)
- [x] Add `SourceFile` to docs of `Reflection` (PR #10630)
- [x] Add `IfMethods.isInline` and `MatchMethods.isInline` (PR  #10625)
- [x] Add `Position.apply(source, start, end)` and remove equivalent reporting API (PR #10629)
- [x] Change signature to `def sourceCode: Option[String]` in `PositionMethods` (PR #10626)
- [x] Change signature to `def content: Option[String]` in `SourceFileMethods` (PR #10626)
- [x] Replace `Source.path` with ` SourceFile.current: SourceFile` and remove `Source` (PR #10626)
- [ ] ~Try to represent `SummonFrom` in the compiler as as `{x => x match { case ... }}` and remove `SummonFrom` (see issue #10624)~
- [x] Define `Printer` type class for `show`: `tree.show(using Printer.Tree)` (Extractors), `tree.show(using Printer.Short)`, `tree.show(using Printer.Ansi)` (PR #10661)

**Comment by abgruszecki** [comment]
I still think we should do something about `SourceFile#jpath`. In particular, I think that in Tasty Inspector, this method should return precisely the path contained in Tasty files. Which brings the question, what format should the paths in those files have. There's a platform-indepedent format here: Windows paths can be normalised to use `/` as the separator. Since we can normalise paths, I think we should do that - otherwise, to understand the Tasty files, the user will need to normalise the paths themselves, because they won't know whether they came from Windows or ~a normal~ another OS.

This, in turn, means that from the perspective of Tasty Inspector, there's no reason to make `SourceFile#jpath` return a Java `Path`. Question is, what does staging see there? An absolute path, or a relative one?

/cc @nicolasstucki @smarter

**Comment by nicolasstucki** [comment]
It should be a relative path. The documentation still needs to be updated. It is the path that is kept in the TASTy. More details can be found on #10430.

**Comment by abgruszecki** [comment]
So is it _always_ a relative path?

**Comment by abgruszecki** [comment]
Also asking, since I found out that after all `associatedFile` _is_ set when loading symbols from Tasty. I think it makes sense to make `jpath` always be the relative path, and also to expose `associatedFile`, which is an absolute path to the file from which a symbol was loaded.
