### ISSUE TITLE
Release Scala 3.0.0-M3

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#10814]
- [x] Finalize release
  - [x] Look at the milestone of the version being released. Move all the open issues from it to the next milestone.
  - [x] Merge branch `M2` into `master` to guarantee that all of the commits are propagated to `master`
- [x] Publish artifacts to Maven via CI
  - [x] Create branch `M3` from `master`
  - [x] On `M3`, set `baseVersion` and tag it as `3.0.0-M3`
  - [x] On `master`, set `baseVersion` to `RC1`
- [ ] Update `scalaVersion` (and, if applicable, the `sbt-dotty` version) in the Dotty ecosystem projects
  - [x] https://github.com/scala/scala3-example-project [![Build Status](https://travis-ci.org/scala/scala3-example-project.svg?branch=master)](https://travis-ci.org/scala/scala3-example-project)
    - [x] Committed to `master` (https://github.com/scala/scala3-example-project/pull/48)
  - [x] https://github.com/scala/scala3-example-project/tree/mill
  - [x] https://github.com/scala/scala3.g8 [![Build Status](https://travis-ci.org/scala/scala3.g8.svg?branch=master)](https://travis-ci.org/scala/scala3.g8/)
    - [x] Committed to `master` (https://github.com/scala/scala3.g8/pull/35)
  - [x] https://github.com/scala/scala3-cross.g8 [![Build Status](https://travis-ci.org/scala/scala3-cross.g8.svg?branch=master)](https://travis-ci.org/scala/scala3-cross.g8/)
    - [x] Committed to `master` (https://github.com/lampepfl/scala3-cross.g8/pull/14)
  - [x] https://github.com/lampepfl/scala3-staging.g8 [![Build Status](https://travis-ci.org/scala/scala3-staging.g8.svg?branch=master)](https://travis-ci.org/lampepfl/scala3-staging.g8)
    - [x] Committed to `master` (https://github.com/scala/scala3-staging.g8/pull/13)
  - [x] https://github.com/scala/scala3-tasty-inspector.g8 [![Build Status](https://travis-ci.org/scala/scala3-tasty-inspector.g8.svg?branch=master)](https://travis-ci.org/scala/scala3-tasty-inspector.g8)
    - [x] Committed to `master` (https://github.com/scala/scala3-tasty-inspector.g8/pull/6)
  - [ ] https://github.com/lampepfl/homebrew-brew [![Build Status](https://travis-ci.org/lampepfl/homebrew-brew.svg?branch=master)](https://travis-ci.org/lampepfl/homebrew-brew)
    - [x] Committed to `master`
    - SHA256 sum for the artifact: `wget -q -O- https://github.com/lampepfl/dotty/releases/download/<rc-version>/sha256sum.txt | grep ".tar.gz"`
  - [ ] https://github.com/lampepfl/packtest [![Build Status](https://travis-ci.org/lampepfl/packtest.svg?branch=master)](https://travis-ci.org/lampepfl/packtest)
    - [x] Committed to `master`
  - [x] https://github.com/lampepfl/xml-interpolator [![Build Status](https://travis-ci.org/lampepfl/xml-interpolator.svg?branch=master)](https://travis-ci.org/lampepfl/xml-interpolator)
    - [x] PR submitted (https://github.com/lampepfl/xml-interpolator/pull/29)
    - [x] PR merged
  - [x] https://github.com/scalacenter/scastie
    - [x] PR submitted (scalacenter/scastie#487)
    - [x] PR merged
    - [x] https://scastie.scala-lang.org/ -> Build Settings -> Dotty mentions `<rc-version>`
  - [x] Dotty reference compiler [![Dotty CI](https://github.com/lampepfl/dotty/workflows/Dotty%20CI/badge.svg?branch=master)](https://github.com/lampepfl/dotty/actions?query=branch%3Amaster)
    - [x] PR submitted (#10828)
    - [x] PR merged
  - [ ] Scalac [![Build Status](https://travis-ci.org/scala/scala.svg?branch=2.13.x)](https://travis-ci.org/scala/scala)
    - [x] PR submitted (scala/scala#9395)
    - [ ] PR merged
  - [ ] Update the dotty-repl Coursier [app definition](https://github.com/coursier/apps/blob/master/apps/resources/dotty-repl.json)
    - [x] PR submitted (coursier/apps#79)
    - [ ] PR merged
- [ ] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [ ] Publish Blog Post on dotty.epfl.ch
  - [ ] Make an announcement thread on https://contributors.scala-lang.org
  - [ ] Tweet the announcement blog post on https://twitter.com/scala_lang

[Instructions on how to release](https://dotty.epfl.ch/docs/contributing/procedures/release.html)

**Comment by tpolecat** [comment]
Would it be possible to include "update the [dotty-repl Coursier app definition](https://github.com/coursier/apps/blob/master/apps/resources/dotty-repl.json)" in this list as well?

**Comment by nicolasstucki** [comment]
The instructions link is outdated. Here is the new one https://dotty.epfl.ch/docs/contributing/procedures/release.html
We need to update it in the release todo instructions template.

**Comment by nicolasstucki** [comment]
We are also missing https://github.com/scala/scala3-tasty-inspector.g8

**Comment by nicolasstucki** [comment]
@anatoliykmetyuk where did you get the todo list from? `docs/docs/contributing/checklist.sh` seems to be quite outdated.

**Comment by nicolasstucki** [comment]
@anatoliykmetyuk I've updated the links in the first comment. Could you sync those with the template?

**Comment by anatoliykmetyuk** [comment]
@nicolasstucki all the release scripts are located at https://github.com/lampepfl/dotty-release-scripts. I updated the checklist: https://github.com/lampepfl/dotty-release-scripts/commit/a32d995ee2ad9b32a0dfcde15a3d7ebdb368b736

@tpolecat done.
