### ISSUE TITLE
Release RC1

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#11416]
- [x] Finalize release
  - [x] Look at the milestone of the version being released. Move all the open issues from it to the next milestone.
  - [x] Merge branch of the previous release into `master` to guarantee that all of the commits are propagated to `master`
- [x] Publish artifacts to Maven via CI
  - [x] Create branch `3.0.0-RC1` from `master`
  - [x] On that branch, set `baseVersion` and tag it as `3.0.0-RC1`
  - [x] On `master`, set `baseVersion` to the next version to be released
- [x] Update `scalaVersion` (and, if applicable, the `sbt-dotty` version) in the Dotty ecosystem projects
  - [x] https://github.com/scala/scala3-example-project [![Build Status](https://travis-ci.org/scala/scala3-example-project.svg?branch=master)](https://travis-ci.org/scala/scala3-example-project)
  - [x] https://github.com/scala/scala3-example-project/tree/mill
  - [x] https://github.com/scala/scala3.g8 [![Build Status](https://travis-ci.org/scala/scala3.g8.svg?branch=master)](https://travis-ci.org/scala/scala3.g8/)
  - [x] https://github.com/scala/scala3-cross.g8 [![Build Status](https://travis-ci.org/scala/scala3-cross.g8.svg?branch=master)](https://travis-ci.org/scala/scala3-cross.g8/)
  - [x] https://github.com/lampepfl/scala3-staging.g8 [![Build Status](https://travis-ci.org/scala/scala3-staging.g8.svg?branch=master)](https://travis-ci.org/lampepfl/scala3-staging.g8)
  - [x] https://github.com/scala/scala3-tasty-inspector.g8 [![Build Status](https://travis-ci.org/scala/scala3-tasty-inspector.g8.svg?branch=master)](https://travis-ci.org/scala/scala3-tasty-inspector.g8)
  - [x] https://github.com/lampepfl/homebrew-brew [![Build Status](https://travis-ci.org/lampepfl/homebrew-brew.svg?branch=master)](https://travis-ci.org/lampepfl/homebrew-brew)
    - SHA256 sum for the artifact: `wget -q -O- https://github.com/lampepfl/dotty/releases/download/<rc-version>/sha256sum.txt | grep ".tar.gz"`
  - [x] https://github.com/lampepfl/packtest [![Build Status](https://travis-ci.org/lampepfl/packtest.svg?branch=master)](https://travis-ci.org/lampepfl/packtest)
  - [x] https://github.com/lampepfl/xml-interpolator [![Build Status](https://travis-ci.org/lampepfl/xml-interpolator.svg?branch=master)](https://travis-ci.org/lampepfl/xml-interpolator)
    - [x] PR submitted
    - [x] PR merged
  - [x] https://github.com/scalacenter/scastie
    - [x] PR submitted
    - [x] PR merged
    - [x] https://scastie.scala-lang.org/ -> Build Settings -> Dotty mentions `<rc-version>`
  - [x] Dotty reference compiler [![Dotty CI](https://github.com/lampepfl/dotty/workflows/Dotty%20CI/badge.svg?branch=master)](https://github.com/lampepfl/dotty/actions?query=branch%3Amaster)
    - [x] PR submitted
    - [x] PR merged
  - [x] Scalac [![Build Status](https://travis-ci.org/scala/scala.svg?branch=2.13.x)](https://travis-ci.org/scala/scala)
    - [x] PR submitted
    - [x] PR merged
  - [x] Update the dotty-repl Coursier [app definition](https://github.com/coursier/apps/blob/master/apps/resources/dotty-repl.json)
- [x] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Publish Blog Post on dotty.epfl.ch
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

[Instructions on how to release](https://dotty.epfl.ch/docs/contributing/procedures/release.html)

**Comment by anatoliykmetyuk** [comment]
Pending #11410.

**Comment by anatoliykmetyuk** [comment]
Related PRs:

- [Dotty](https://github.com/lampepfl/dotty/pull/11433)
- [Scala](https://github.com/scala/scala/pull/9502)
- [Scastie](https://github.com/scalacenter/scastie/pull/493)
- [Coursier Apps](https://github.com/coursier/apps/pull/85)

**Comment by larsrh** [comment]
We need a new release of sbt-dotty, too: f75e6fb3c59fae896b5b9e46c8bb294f04042924

**Comment by smarter** [comment]
sbt-dotty 0.5.3 release job: https://github.com/lampepfl/dotty/actions/runs/572300705

**Comment by ShapelessCat** [comment]
[3.0.0-RC1 release page](https://github.com/lampepfl/dotty/releases/tag/3.0.0-RC1) mentions "Allow `with` after class [#11157](https://github.com/lampepfl/dotty/pull/11157)" in the **Syntax** section, and I think this is NOT right.
#11213 already reverted #11157.

Here is the final decision of keep using `:`: https://contributors.scala-lang.org/t/feedback-sought-optional-braces/4702/588.

**Comment by bishabosha** [comment]
@ShapelessCat I can do it in the repl
```scala
Scala compiler version 3.0.0-RC1 -- Copyright 2002-2021, LAMP/EPFL
scala> class Foo with
     |   def foo = 23
     | 
// defined class Foo
```

**Comment by ShapelessCat** [comment]
@bishabosha Does this mean the after classes `with` syntax is a syntax that we plan to remove, but we haven't removed it completely?
I can also see a discussion in Add RC1 blog article #11417.

**Comment by bishabosha** [comment]
@ShapelessCat I am not sure what's happening, but thank you for linking to the discussion, I added my example there.
