### ISSUE TITLE
Release 3.0.0-RC3

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#12146]
- [x] Finalize release
  - [x] Look at the milestone of the version being released. Move all the open issues from it to the next milestone.
- [x] Publish artifacts to Maven via CI
  - [x] Set `baseVersion` and tag it as `3.0.0-RC3`
- [x] Update `scalaVersion` (and, if applicable, the `sbt-dotty` version) in the Dotty ecosystem projects
  - [x] https://github.com/scala/scala3-example-project [![Build Status](https://travis-ci.org/scala/scala3-example-project.svg?branch=master)](https://travis-ci.org/scala/scala3-example-project)
  - [x] https://github.com/scala/scala3-example-project/tree/mill (outdated link)
  - [x] https://github.com/scala/scala3.g8 [![Build Status](https://travis-ci.org/scala/scala3.g8.svg?branch=master)](https://travis-ci.org/scala/scala3.g8/)
  - [x] https://github.com/scala/scala3-cross.g8 [![Build Status](https://travis-ci.org/scala/scala3-cross.g8.svg?branch=master)](https://travis-ci.org/scala/scala3-cross.g8/)
  - [x] https://github.com/lampepfl/scala3-staging.g8 [![Build Status](https://travis-ci.org/scala/scala3-staging.g8.svg?branch=master)](https://travis-ci.org/lampepfl/scala3-staging.g8)
  - [x] https://github.com/scala/scala3-tasty-inspector.g8 [![Build Status](https://travis-ci.org/scala/scala3-tasty-inspector.g8.svg?branch=master)](https://travis-ci.org/scala/scala3-tasty-inspector.g8)
  - [x] https://github.com/lampepfl/homebrew-brew [![Build Status](https://travis-ci.org/lampepfl/homebrew-brew.svg?branch=master)](https://travis-ci.org/lampepfl/homebrew-brew)
  - [ ] https://github.com/lampepfl/packtest [![Build Status](https://travis-ci.org/lampepfl/packtest.svg?branch=master)](https://travis-ci.org/lampepfl/packtest)
  - [x] https://github.com/lampepfl/xml-interpolator [![Build Status](https://travis-ci.org/lampepfl/xml-interpolator.svg?branch=master)](https://travis-ci.org/lampepfl/xml-interpolator)
  - [ ] https://github.com/scalacenter/scastie
    - [x] PR submitted
    - [ ] PR merged
    - [ ] https://scastie.scala-lang.org/ -> Build Settings -> Dotty mentions `<rc-version>`
  - [ ] Dotty reference compiler [![Dotty CI](https://github.com/lampepfl/dotty/workflows/Dotty%20CI/badge.svg?branch=master)](https://github.com/lampepfl/dotty/actions?query=branch%3Amaster)
    - [x] PR submitted
    - [ ] PR merged
  - [ ] Scalac [![Build Status](https://travis-ci.org/scala/scala.svg?branch=2.13.x)](https://travis-ci.org/scala/scala)
    - [x] PR submitted
    - [ ] PR merged
  - [x] Update the dotty-repl Coursier [app definition](https://github.com/coursier/apps/blob/master/apps/resources/dotty-repl.json)
- [x] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Publish Blog Post on dotty.epfl.ch
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

[Instructions on how to release](https://dotty.epfl.ch/docs/contributing/procedures/release.html)

**Comment by griggt** [comment]
Publishing from the `release-3.0.0` branch has some (possibly unforeseen) side effects:

 - the `dottyLatestNightlyBuild` feature of `sbt-dotty` is temporary broken (see https://github.com/lampepfl/dotty/pull/12144#issuecomment-822779647)
 - the documentation at https://dotty.epfl.ch/api/index.html was yesterday for a 3.0.1 nightly, is currently for 3.0.0-RC3, and tomorrow will be for a 3.0.1 nightly again

**Comment by nicolasstucki** [comment]
We still need to create a `scala3-mill-example-project` instead of using the old https://github.com/scala/scala3-example-project/tree/mill branch that needs to be removed from that repo.

**Comment by anatoliykmetyuk** [comment]
> Can you take over and create scala3-mill-example-project

Done: https://github.com/scala/scala3-mill-example-project
I also added you @nicolasstucki to admins in `scala`, so you should be able to create new projects now.
