### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#12441]
- [x] Look at the milestone of the version being released. Move all the open issues from it to the next milestone.
- [x] On `release-3.0.0`, set `baseVersion` and tag it as `3.0.0`
- [x] [Release ecosystem](https://www.notion.so/Scala-3-Ecosystem-Status-2460b396a89b478e8d4fa47ac27abbbd)
- [x] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Publish Blog Post on dotty.epfl.ch
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

**Comment by mpilquist** [comment]
FYI, the scodec build failure can be fixed by bumping to scodec main branch HEAD.

Not sure why it didn't fail until the final release -- I'm guessing b/c the community build was running with experimental features enabled,

Here's the line on HEAD: https://github.com/scodec/scodec/blob/main/unitTests/src/test/scala/scodec/examples/ProductsExample.scala#L61

**Comment by griggt** [comment]
`scodec` was supposed to be skipped in the community build for non-experimental runs:

https://github.com/lampepfl/dotty/blob/cf272111c02e8a11df9308c6a7dbd8df7de97d26/community-build/test/scala/dotty/communitybuild/CommunityBuildTest.scala#L119

but this is the definition of `compilerSupportExperimental`:

https://github.com/lampepfl/dotty/blob/cf272111c02e8a11df9308c6a7dbd8df7de97d26/community-build/src/scala/dotty/communitybuild/projects.scala#L13-L14

and during the community build runs of the release pipeline, the compiler version is still `3.0.0-bin-SNAPSHOT`:

> Building scodec with dotty-bootstrapped 3.0.0-bin-SNAPSHOT...
https://github.com/lampepfl/dotty/runs/2567076730?check_suite_focus=true#step:8:1283

because the `RELEASEBUILD` env var is not set in the community build jobs

**Comment by larsrh** [comment]
Is this the correct artifact name? https://oss.sonatype.org/content/repositories/public/org/scala-lang/scala3-compiler_3.0.0-nonbootstrapped/

**Comment by larsrh** [comment]
ScalaCheck does not build:

```
sbt:scalacheck> jvm/update
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn]  Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last jvm / update for the full output
[error] (jvm / update) sbt.librarymanagement.ResolveException: Error downloading org.scala-lang:scala3-library_3:3.0.0
[error]   Not found
[error]   Not found
[error]   not found: /home/lars/.ivy2/localorg.scala-lang/scala3-library_3/3.0.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/org/scala-lang/scala3-library_3/3.0.0/scala3-library_3-3.0.0.pom
[error] Total time: 1 s, completed May 12, 2021 8:12:53 PM
```

**Comment by smarter** [comment]
> Is this the correct artifact name?

It isn't, fixed by https://github.com/lampepfl/dotty/pull/12452

**Comment by smarter** [comment]
Third time's the charm? https://github.com/lampepfl/dotty/actions/runs/836876424

**Comment by smarter** [comment]
(there's a good chance this is going to fail because of the awkward partially-released status we're in)

**Comment by smarter** [comment]
Well it failed before that in the community build because mill is using the wrong binary suffix for 3.0.0-bin-SNAPSHOT, it didn't fail before because our own build was also using that incorrect suffix before. We could go fix that upstream in mill but since it won't happen after 3.0.0 its a bit overkill, so we can either turn off mill projects from our community build for the release, or make sure the community build is run with scalaVersion set to 3.0.0 (so `RELEASEBUILD` should be set in all jobs triggered by a tag instead of only setting in the jobs related to publishing the release).

**Comment by anatoliykmetyuk** [comment]
Attempt number 3, this time without the community_build_c: https://github.com/lampepfl/dotty/actions/runs/838317553

**Comment by xuwei-k** [comment]
😢 

https://github.com/lampepfl/dotty/runs/2574228040?check_suite_focus=true#step:8:1050

```
Error:  Failed to promote the repository
Error:  Activity release started:2021-05-13T09:32:30.634Z, stopped:
Error:      Failed: RepositoryWritePolicy, failureMessage:Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/org/scala-lang/scala3-interfaces/3.0.0/scala3-interfaces-3.0.0.jar'
java.lang.Exception: Failed to promote the repository
	at xerial.sbt.NexusRESTService.promoteStage(NexusClient.scala:477)
```

https://repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.0.0/

**Comment by gabro** [comment]
As @smarter mentioned, some artifacts were published correctly and some weren't, so there's no way now to do an automatic release from CI. I suppose the only viable option is to manually publish the missing artifacts

**Comment by ScalaWilliam** [comment]
Watching this with a keen eye!

**Comment by mr-git** [comment]
other option is to make 3.0.1 release

**Comment by alexandru** [comment]
This is awesome ❤️

@anatoliykmetyuk you mentioned a "Release Ecosystem" link.

From where is that list coming from, and how can we add to it libraries that were released already for Scala 3.0.0?

**Comment by anatoliykmetyuk** [comment]
The "Release Ecosystem" link is meant to track the status of projects the release cycle of which is in any way managed by LAMP and Scala Center. The projects in question are meant to be tooling, getting-started materials, and other critical components without which Scala users would have hard times on new releases. On each release cycle, our teams release the listed components in a semi-automatic way. For other wider ecosystem that is not as critical, the best tool so far would be [Scaladex](https://index.scala-lang.org/).

The current automation that is used to release the critical ecosystem is [dotty-release-scripts](https://github.com/lampepfl/dotty-release-scripts). It contains the data associated with the release procedure under the [data](https://github.com/lampepfl/dotty-release-scripts/tree/master/data) folder, in Markdown and YAML. The ecosystem projects data is stored in a [separate folder](https://github.com/lampepfl/dotty-release-scripts/tree/master/data/projects) where every ecosystem has its own YAML file. Each YAML file describes what to do for each project to bump its version on each release, and the list linked in the issue is based on those YAML files.

If you have tooling, library, or infrastructure the release of which you think must be integrated into the Scala 3 release cycle, you can submit a PR to the above repo adding the YAML description of your project.
