### ISSUE TITLE
Release 3.0.1-RC1

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#12665]
- [x] Look at the milestone of the version being released. Move all the open issues from it to the next milestone.
- [x] Publish artifacts to Maven via CI
  - [x] Create branch `release-3.0.1` from `master`
  - [x] On that branch
    - [x] In `Build.scala`: Set `baseVersion` to `3.0.1-RC1`
    - [x] In `Build.scala`: Set `previousDottyVersion` according to the instructions in the comment to that variable.
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: Set `ExperimentalVersion` to `0` to indicate a stable release; make sure `MajorVersion` and `MinorVersion` are set the same as the last patch release.
    - [x] Tag the branch as `3.0.1-RC1`
  - [x] On `master`, set `baseVersion` to the next version to be released
- [x] [Release ecosystem](https://www.notion.so/Scala-3-Ecosystem-Status-2460b396a89b478e8d4fa47ac27abbbd)
- [x] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Publish Blog Post on dotty.epfl.ch
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

[Instructions on how to release](https://dotty.epfl.ch/docs/contributing/procedures/release.html)

**Comment by smarter** [comment]
>  Release ecosystem

Now that Scala 3 is out and backwards binary-compatible, there is no real need for us to upgrade the whole ecosystem at every release, we can let each project do it at their own pace (and I think https://github.com/scala-steward-org/scala-steward can help automate that for projects who want to)
