### ISSUE TITLE
Release 3.0.1-RC2

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#12900]
- [x] Look at the milestone of the version being released. Move all the open issues from it to the next milestone.
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.0.1` branch
    - [x] In `Build.scala`: Set `baseVersion` to `3.0.1-RC2`
    - [x] In `Build.scala`: Set `previousDottyVersion` according to the instructions in the comment to that variable.
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: Set `ExperimentalVersion` to `0` to indicate a stable release; make sure `MajorVersion` and `MinorVersion` are set correctly for the release.
    - [x] Tag the branch as `3.0.1-RC2`
- [x] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Publish Blog Post on dotty.epfl.ch
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

[Instructions on how to release](https://dotty.epfl.ch/docs/contributing/procedures/release.html)
