### ISSUE TITLE
Release 3.0.1

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#13025]
- [x] Look at the milestone of the version being released. Move all the open issues from it to the next milestone.
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.0.1` branch
    - [x] In `Build.scala`: Set `baseVersion` to `3.0.1`
    - [x] In `Build.scala`: Set `previousDottyVersion` according to the instructions in the comment to that variable.
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: Set `ExperimentalVersion` to `0` to indicate a stable release; make sure `MajorVersion` and `MinorVersion` are set correctly for the release.
    - [x] Tag the branch as `3.0.1`
  - [x] On `master`:
    - [x] In `Build.scala`: Set `baseVersion` to the next version to be released
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.0.1`
    - [x] In `project/MiMaFilters.scala`: Remove all `exclude` filters
- [x] [Release ecosystem](https://www.notion.so/Scala-3-Ecosystem-Status-d75fdf7d124f43fea30be53ca817a3d4)
- [x] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Publish Blog Post on scala-lang.org
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

[Instructions on how to release](https://dotty.epfl.ch/docs/contributing/procedures/release.html)

**Comment by smarter** [comment]
SInce 3.0.2-RC1 should be released at the same time, should its release process be listed in this issue too?

**Comment by anatoliykmetyuk** [comment]
I believe it's best to keep things decoupled and modular – for the sake of simplicity but also since sometimes we may not release RC and stable at the same time. Let's try doing one issue per release.
