### ISSUE TITLE
Release 3.0.2-RC2

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#13356]
- [x] Publish artifacts to Maven via CI
  - [x] On that branch
    - [x] In `Build.scala`: Set `baseVersion` to `3.0.2-RC2`
    - [x] In `Build.scala`: Set `previousDottyVersion` according to the instructions in the comment to that variable.
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: Set `ExperimentalVersion` to `0` to indicate a stable release; make sure `MajorVersion` and `MinorVersion` are set correctly for the release.
    - [x] Tag the branch as `3.0.2-RC2`
- [x] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Make an announcement thread on https://contributors.scala-lang.org
