### ISSUE TITLE
Release 3.0.2

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#13389]
- [x] Look at the milestone of the version being released. Move all the open issues from it to the next milestone.
- [x] Publish artifacts to Maven via CI
  - [x] On that branch
    - [x] In `Build.scala`: Set `baseVersion` to `3.0.2`
    - [x] In `Build.scala`: Set `previousDottyVersion` according to the instructions in the comment to that variable.
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: Set `ExperimentalVersion` to `0` to indicate a stable release; make sure `MajorVersion` and `MinorVersion` are set correctly for the release.
    - [x] Tag the branch as `3.0.2`
  - [x] On `master`:
    - [x] In `Build.scala`: Set `baseVersion` to the next version to be released
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.0.2`
    - [x] In `project/MiMaFilters.scala`: Remove all `exclude` filters
- [x] Update the API documentation
  - [x] Upload it to https://scala-lang.org/api/3.0.2/
  - [x] Update the symlink https://scala-lang.org/api/3.x/ to point to it
- [x] [Release ecosystem](https://www.notion.so/Scala-3-Ecosystem-Status-2460b396a89b478e8d4fa47ac27abbbd)
- [x] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Publish Blog Post on https://scala-lang.org/blog
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang
