### ISSUE TITLE
Release 3.1.0-RC1

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#13390]
- [x] Look at the milestone of the version being released. Move all the open issues from it to the next milestone.
- [x] Publish artifacts to Maven via CI
  - [x] Create branch `release-3.1.0` from `master`
  - [x] On that branch
    - [x] In `Build.scala`: Set `baseVersion` to `3.1.0-RC1`
    - [x] In `Build.scala`: Set `previousDottyVersion` according to the instructions in the comment to that variable.
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: Set `ExperimentalVersion` to `0` to indicate a stable release; make sure `MajorVersion` and `MinorVersion` are set correctly for the release.
    - [x] Tag the branch as `3.1.0-RC1`
  - [x] On `master`:
    - [x] In `Build.scala`: Set `baseVersion` to the next version to be released
- [x] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Make an announcement thread on https://contributors.scala-lang.org

**Comment by nicolasstucki** [comment]
@Kordyjan we have closed all issues/PRs from the 3.1.0 milestone. We should let the CI build and test a nightly build today. We can start the release process tomorrow.
