### ISSUE TITLE
Release 3.1.0-RC2

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#13540]
- [x] Have #13519 merged
- [x] Have #13534 merged
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.1.0` branch
    - [x] In `Build.scala`: Set `baseVersion` to `3.1.0-RC2`
    - [x] In `Build.scala`: Set `previousDottyVersion` according to the instructions in the comment to that variable.
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: Set the correct tasty version according to #13447
    - [x] In `Build.scala`: Set `referenceVersion` to `3.1.0-RC1`
    - [x] Tag the branch as `3.1.0-RC2`
- [x] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Make an announcement thread on https://contributors.scala-lang.org
