### ISSUE TITLE
Release 3.1.0-RC3

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#13672]
- [ ] Publish artifacts to Maven via CI
  - [ ] On that branch
    - [ ] In `Build.scala`: Set `baseVersion` to `3.1.0-RC3`
    - [ ] In `Build.scala`: Set `previousDottyVersion` according to the instructions in the comment to that variable.
    - [ ] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`:  make sure `MajorVersion` and `MinorVersion` are set correctly for the release.
    - [ ] Tag the branch as `3.1.0-RC3`
- [ ] Announce the release
  - [ ] Publish releases for the RC and stable versions on GitHub Releases
  - [ ] Make an announcement thread on https://contributors.scala-lang.org
