### ISSUE TITLE
3.1.0 & 3.1.1-RC1 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#13763]
- [x] Publish 3.1.0 artifacts to Maven via CI
  - [x] On `release-3.1.0` branch
    - [x] In `Build.scala`: Set `baseVersion` to `3.1.0`
    - [x] In `Build.scala`: Set `previousDottyVersion` according to the instructions in the comment to that variable.
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: Set `ExperimentalVersion` to `0` to indicate a stable release; make sure `MajorVersion` and `MinorVersion` are set correctly for the release.
    - [x] Tag the branch as `3.1.0`
  - [x] Publish changelog for 3.1 on GitHub Releases 
  - [x] On `master`:
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.1.0`
    - [x] In `Build.scala`: Set `referenceVersion` to `3.1.0`
    - [x] In `project/MiMaFilters.scala`: Remove all `exclude` filters
 - [x] Publish 3.1.1-RC1 artifacts to Maven via CI
   - [x] Create branch `release-3.1.1` from `master`
   - [x] On that branch
     - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: Set `ExperimentalVersion` to `0` to indicate a stable release; make sure `MajorVersion` and `MinorVersion` are set correctly for the release.
     - [x] Tag the branch as `3.1.1-RC1`
   - [x] On `master`:
     - [x] In `Build.scala`: Set `baseVersion` to 3.1.2-RC1
     - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: make sure `MajorVersion` and `MinorVersion` are set correctly for the 3.1.2.
- [x] Release ecosystem for 3.1.0
- [x] Publish API docs for 3.1.0 stdlib
- [x] Announce the releases
  - [x] Publish Blog Post on dotty.epfl.ch
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang
