### ISSUE TITLE
Release 3.1.1-RC2

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#14110]
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.1.1` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.1.1-RC2`
    - [x] In `Build.scala`: Set `previousDottyVersion` according to the instructions in the comment to that variable.
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: make sure `MajorVersion` and `MinorVersion` are set correctly for the release.
    - [x] Tag the branch as `3.1.1-RC2`
- [x] On `master`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.1.1-RC2`
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Make an announcement thread on https://contributors.scala-lang.org
