### ISSUE TITLE
3.1.1 & 3.1.2-RC1 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#14311]
- [x] Publish 3.1.1 artifacts to Maven via CI
  - [x] On `release-3.1.1` branch
    - [x] In `Build.scala`: Set `baseVersion` to `3.1.1`
    - [x] In `Build.scala`: Set `previousDottyVersion` according to the instructions in the comment to that variable.
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: Set `ExperimentalVersion` to `0` to indicate a stable release; make sure `MajorVersion` and `MinorVersion` are set correctly for the release.
    - [x] Tag the branch as `3.1.1`
  - [x] Publish changelog for 3.1.1 on GitHub Releases 
 - [x] Publish 3.1.2-RC1 artifacts to Maven via CI
   - [x] Wait for green nightly CI build 
   - [x] Create branch `release-3.1.2` from `master`
   - [x] On that branch
     - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: Set `ExperimentalVersion` to `0` to indicate a stable release; make sure `MajorVersion` and `MinorVersion` are set correctly for the release.
     - [x] Tag the branch as `3.1.2-RC1`
- [x] On `master`:
  - [x] In `Build.scala`: Set `previousDottyVersion` to `3.1.1`
  - [x] In `Build.scala`: Set `referenceVersion` to `3.1.2-RC1`
  - [x] In `project/MiMaFilters.scala`: Remove all `exclude` filters
  - [x] In `Build.scala`: Set `baseVersion` to 3.1.3-RC1
  - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: make sure `MajorVersion` and `MinorVersion` are set correctly for the 3.1.3.
- [x] Release ecosystem for 3.1.1
- [x] Wait for confirmation from tooling:
  - [x] Metals
  - [x] Scala CLI
  - [x] Scala Native
- [x] Notify [Scala Steward](https://github.com/scala-steward-org/scala-steward/blob/master/modules/core/src/main/resources/default.scala-steward.conf#L3)
- [x] Release to SDKMAN
- [x] Publish API docs for 3.1.1 stdlib
- [x] Announce the releases
  - [x] Publish Blog Post on dotty.epfl.ch
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

**Comment by WojciechMazur** [comment]
Scala Native artifacts for Scala 3.1.1 are on their way to the Maven repository

**Comment by smarter** [comment]
A step that should be added to the list: close the corresponding milestone in https://github.com/lampepfl/dotty/milestones (and open a new milestone if needed with a date six weeks in the future).
