### ISSUE TITLE
3.1.2 & 3.1.3-RC1 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#14731]
- [x] Close corresponding milestone
- [x] Publish 3.1.2 artifacts to Maven via CI
  - [x] On `release-3.1.2` branch
    - [x] In `Build.scala`: Set `baseVersion` to `3.1.2`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.1.1`
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: Set `ExperimentalVersion` to `0` to indicate a stable release; make sure `MajorVersion` and `MinorVersion` are set correctly for the release.
    - [x] Tag the branch as `3.1.2`
  - [x] Publish changelog for 3.1.2 on GitHub Releases 
 - [x] Publish 3.1.3-RC1 artifacts to Maven via CI
   - [x] Create branch `release-3.1.3` from `master`
   - [x] On that branch
     - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: Set `ExperimentalVersion` to `0` to indicate a stable release; make sure `MajorVersion` and `MinorVersion` are set correctly for the release.
     - [x] Tag the branch as `3.1.3-RC1`
- [x] On `master`:
  - [x] In `Build.scala`: Set `previousDottyVersion` to `3.1.2`
  - [x] In `Build.scala`: Set `referenceVersion` to `3.1.3-RC1`
  - [x] In `project/MiMaFilters.scala`: Remove all `exclude` filters
  - [x] In `Build.scala`: Set `baseVersion` to 3.2.0-RC1
  - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: make sure `MajorVersion` and `MinorVersion` are set correctly for the 3.2.0.
- [x] Release ecosystem for 3.1.2
- [x] Wait for confirmation from tooling:
  - [x] Metals
  - [x] Scala CLI
  - [x] Scala Native
  - [x] SBT (support for release flags)
- [x] Notify [Scala Steward](https://github.com/scala-steward-org/scala-steward/blob/master/modules/core/src/main/resources/default.scala-steward.conf#L3)
- [x] Release to SDKMAN
- [x] Publish API docs for 3.1.2 stdlib
- [x] Announce the releases
  - [x] Publish Blog Post on dotty.epfl.ch (https://github.com/lampepfl/dotty/issues/14614)
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

**Comment by smarter** [comment]
> In Build.scala: Set baseVersion to 3.2.0-RC1

This task list item is marked as checked, but baseVersion is currently 3.1.3-RC1 on main: https://github.com/lampepfl/dotty/blob/ebe3d54c3774bcaacad6696ccd2c444b637969b3/project/Build.scala#L62

**Comment by Kordyjan** [comment]
Something went wrong. Thanks for pointing it out.

**Comment by smarter** [comment]
>  In project/MiMaFilters.scala: Remove all exclude filters

This is also checked but doesn't seem to have been done.

**Comment by Kordyjan** [comment]
> This is also checked but doesn't seem to have been done.

It should be rephrased as `Remove all exclude filters that are no longer applicable`

And it was done: https://github.com/lampepfl/dotty/commit/376d954d27032e73f3c61d377f9836e2862c3ebc#diff-66a10df3a732cc2c54a4831d5130bad719649c0cf3b4415525c657c5b73403db

**Comment by Kordyjan** [comment]
Oh, I see. I indeed did things in reverse since it doesn't matter for patch releases/

**Comment by smarter** [comment]
> [X] Close corresponding milestone

3.1.3-RC1 wasn't closed, so I just closed it and opened 3.1.3 to track backports.
