### ISSUE TITLE
3.1.2-RC3 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#14745]
- [x] Merge https://github.com/lampepfl/dotty/pull/14744
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.1.2` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.1.2-RC3`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.1.2-RC2`
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala`: make sure `MajorVersion` and `MinorVersion` are set correctly for the release.
    - [x] Tag the branch as `3.1.2-RC3`
- [x] On `master`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.1.2-RC3`
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Make an announcement thread on https://contributors.scala-lang.org
