### ISSUE TITLE
3.1.3-RC3 release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#15168]
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.1.3` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.1.3-RC3`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.1.3-RC2`
    - [x] in `changelogs` add file with a changelog
    - [x] Tag the branch as `3.1.2-RC3`
- [x] On `master`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.1.3-RC3`
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Make an announcement thread on https://contributors.scala-lang.org
