### ISSUE TITLE
3.1.3-RC5 release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#15386]
- [x] Wait until backports are merged:
  - [x] #15388
  - [x] #15389 
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.1.3` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.1.3-RC5`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.1.3-RC4`
    - [x] in `changelogs` add file with a changelog
    - [x] Tag the branch as `3.1.3-RC5`
- [x] On `master`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.1.3-RC5`
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Make an announcement thread on https://contributors.scala-lang.org

**Comment by WojciechMazur** [comment]
The open community build has failed for 61 out of 811 projects, 16 projects failed in the runtime (tests), remaining 45 are compilation / scaladoc failures. Of course, some projects might have failed due to source-compatibility reasons with Scala 3.0.x
https://scala3.westeurope.cloudapp.azure.com/job/runBuild/78/
