### ISSUE TITLE
3.1.3 & 3.2.0-RC1 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#15436]
- [x] Close the 3.1.3 milestone
- [x] Publish 3.1.3 artifacts to Maven via CI
  - [x] On `release-3.1.3` branch
    - [x] In `Build.scala`: Set `baseVersion` to `3.1.3`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.1.2`
    - [x] In `changelogs` add file with a changelog
    - [x] Tag the branch as `3.1.2`
- [x] On `main` (https://github.com/lampepfl/dotty/pull/15438):
  - [x] In `Build.scala`: Set `previousDottyVersion` to `3.1.3`
  - [x] In `Build.scala`: Set `referenceVersion` to `3.1.3`
- [x] Close the [3.2.0-RC1 milestone](https://github.com/lampepfl/dotty/milestone/36)
- [x] Create [`3.2.0 backports` milestone](https://github.com/lampepfl/dotty/milestone/42)
- [x] Publish 3.2.0-RC1 artifacts to Maven via CI
   - [x] Create branch `release-3.2.0` from `main`
   - [x] On that branch
     - [x] In `changelogs` add file with a changelog
     - [x] Tag the branch as `3.2.0-RC1`
- [x] On `main`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.2.0-RC1`
  - [x] In `project/MiMaFilters.scala`: Remove all unnecessary `exclude` filters
  - [x] In `Build.scala`: Set `baseVersion` to 3.2.1-RC1
- [x] Release ecosystem for 3.1.3
- [x] Wait for confirmation from tooling:
  - [x] Metals
  - [x] Scala CLI
  - [x] Scala Native
- [x] Release to SDKMAN
- [x] Publish API docs for 3.1.3 stdlib
- [x] Announce the releases
  - [x] Make both GitHub releases public
  - [x] Publish Blog Post on dotty.epfl.ch (https://github.com/scala/scala-lang/pull/1393)
  - [x] Open the 3.2.0 tracking thread https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

**Comment by griggt** [comment]
Just a heads-up: although `3.2.0-RC1` has been tagged, for some reason the workflow ran as a normal push workflow rather than a release workflow, so no artifacts were published: https://github.com/lampepfl/dotty/actions/runs/2503916802

Also, the Windows CI is failing, seems to be from the merge of #14882

**Comment by WojciechMazur** [comment]
Scala Native compiler plugins for 3.1.3 are published (for SN versions 0.4.3 and 0.4.4)
