### ISSUE TITLE
3.2.0-RC2 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#15601]
- [ ] Publish artifacts to Maven via CI
  - [ ] On `release-3.2.0` branch:
    - [ ] In `Build.scala`: Set `baseVersion` to `3.2.0-RC2`
    - [ ] In `Build.scala`: Set `previousDottyVersion` to `3.2.0-RC1`
    - [ ] in `changelogs` add file with a changelog
    - [ ] Tag the branch as `3.2.0-RC2`
- [ ] On `master`:
  - [ ] In `Build.scala`: Set `referenceVersion` to `3.2.0-RC2`
- [ ] Announce the release
  - [ ] Publish release on GitHub Releases
  - [ ] Comment on the announcement thread on https://contributors.scala-lang.org

**Comment by bishabosha** [comment]
we need to backport https://github.com/lampepfl/dotty/pull/15593
