### ISSUE TITLE
3.2.0-RC3 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#15762]
- [x] Merge all backported PRs:
  - [x] #15751
  - [x] #15752
  - [x] #15753
  - [x] #15754
  - [x] #15755
  - [x] #15757
  - [x] #15758 
  - [x] #15760 
  - [x] #15761 
  - [x] #15745
    - [x]  Is waiting for review of #15739 
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.2.0` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.2.0-RC3`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.2.0-RC2`
    - [x] in `changelogs` add file with a changelog
    - [x] Tag the branch as `3.2.0-RC3`
- [x] On `master`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.2.0-RC3`
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Comment on the announcement thread on https://contributors.scala-lang.org/t/3-2-0-release-thread/5773

**Comment by Kordyjan** [comment]
Release job: https://github.com/lampepfl/dotty/actions/runs/2745568269
