### ISSUE TITLE
3.2.0-RC4 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#15873]
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.2.0` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.2.0-RC4`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.2.0-RC3`
    - [x] in `changelogs` add file with a changelog
    - [x] Tag the branch as `3.2.0-RC4`
- [x] On `main` branch:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.2.0-RC4`
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Comment on the announcement thread on https://contributors.scala-lang.org

**Comment by WojciechMazur** [comment]
No new regressions were found in the full [Open Community Build](https://scala3.westeurope.cloudapp.azure.com/job/runBuild/14/)
Tested projects: 881
Failed: 39
