### ISSUE TITLE
3.2.0 & 3.2.1-RC1 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#15935]
- [ ] Close the [3.2.0 backports milestone](https://github.com/lampepfl/dotty/milestone/42)
- [ ] Publish 3.2.0 artifacts to Maven Central via CI
  - [ ] On `release-3.2.0` branch:
    - [ ] In `Build.scala`: Set `baseVersion` to `3.2.0`
    - [ ] In `Build.scala`: Set `previousDottyVersion` to `3.1.3`
    - [ ] In `TastyFormat.scala`: Change tasty version to `28.2-0`
    - [ ] In `changelogs`: Add file with the changelog
    - [ ] Tag the branch as `3.2.0`
- [ ] On `main`:
  - [ ] In `Build.scala`: Set `previousDottyVersion` to `3.2.0`
  - [ ] In `Build.scala`: Set `referenceVersion` to `3.2.0`
  - [ ] In `TastyFormat.scala`: Change tasty version to `28.3-1`
  - [ ] Adjust the `MiMaFilter.scala`
- [ ] Close the [3.2.1-RC1 milestone](https://github.com/lampepfl/dotty/milestone/43)
- [ ] Create `3.2.1 backports` milestone
- [ ] Create `3.2.2-RC1` milestone
- [ ] Publish 3.2.1-RC1 artifacts to Maven via CI
   - [ ] Create branch `release-3.2.1` from `main`
   - [ ] On that branch
     - [ ] In `changelogs`: Add file with athechangelog
     - [ ] In `TastyFormat.scala`: Change tasty version to `28.2-0`
     - [ ] Tag the branch as `3.2.0-RC1`
- [ ] On `main`:
  - [ ] In `Build.scala`: Set `referenceVersion` to `3.2.1-RC1`
  - [ ] In `Build.scala`: Set `baseVersion` to 3.2.2-RC1
  - [ ] Adjust the `MiMaFilter.scala`
- [ ] Release ecosystem for 3.2.0
- [ ] Wait for confirmation from tooling:
  - [ ] Metals
  - [ ] Scala CLI
  - [ ] Scala Native
- [ ] Release to SDKMAN
- [ ] Publish API docs for 3.2.0 stdlib
- [ ] Announce the releases
  - [ ] Make both GitHub releases public
  - [ ] Publish Blog Post on scala-lang.org
  - [ ] Open the 3.2.1 tracking thread https://contributors.scala-lang.org
  - [ ] Tweet the announcement blog post on https://twitter.com/scala_lang

**Comment by bishabosha** [comment]
> Publish API docs for 3.2.0 stdlib

@Kordyjan how is this step specified? because the docs sources are not updated, see https://github.com/lampepfl/dotty/issues/16201
