### ISSUE TITLE
3.2.1-RC2 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#16048]
- [x] Backport relevant changes:
  - [x] #16044
  - [x] #16045
  - [x] #16046
  - [x] #16047 
- [ ] Publish artifacts to Maven via CI
  - [x] On `release-3.2.1` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.2.1-RC2`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.2.1-RC1`
    - [x] in `changelogs` add file with a changelog
    - [x] Tag the branch as `3.2.1-RC2`
- [x] On `main` (https://github.com/lampepfl/dotty/pull/16054):
  - [x] In `Build.scala`: Set `referenceVersion` to `3.2.1-RC2`
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Comment on the announcement thread on https://contributors.scala-lang.org/t/3-2-1-release-thread/5912
