### ISSUE TITLE
3.2.1-RC3 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#16198]
- [x] Merge relevant backports:
  - [x] #16196
  - [x] #16197
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.2.1` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.2.1-RC3`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.2.1-RC2`
    - [x] in `changelogs` add file with a changelog
    - [x] Tag the branch as `3.2.1-RC3`
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Comment on the announcement thread on https://contributors.scala-lang.org
