### ISSUE TITLE
3.2.1 & 3.2.2-RC1 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#16249]
- [x] Close the [3.2.1 backports milestone](https://github.com/lampepfl/dotty/milestone/44)
- [x] Publish 3.2.1 artifacts to Maven Central via CI
  - [x] On `release-3.2.1` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.2.1`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.2.0`
    - [x] In `changelogs`: Add file with the changelog
    - [x] Tag the branch as `3.2.1`
- [x] On `main`:
  - [x] In `Build.scala`: Set `previousDottyVersion` to `3.2.1`
  - [x] In `Build.scala`: Set `referenceVersion` to `3.2.1`
- [x] Create `3.2.2 backports` milestone
- [x] Publish 3.2.2-RC1 artifacts to Maven via CI
   - [x] Create branch `release-3.2.2` from `main`
   - [x] On that branch
     - [x] In `changelogs`: Add file with the changelog
     - [x] In `TastyFormat.scala`: Change tasty version to `28.2-0`
     - [x] Tag the branch as `3.2.2-RC1`
- [x] On `main`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.2.2-RC1`
  - [x] In `Build.scala`: Set `baseVersion` to 3.3.0-RC1
- [x] Release ecosystem for 3.2.1
- [x] Synchronize the `language-reference-stable` branch with the release branch.
- [x] Wait for confirmation from tooling:
  - [x] Metals
  - [x] Scala CLI
  - [x] Scala Native
- [x] Release to SDKMAN
- [x] Publish API docs for 3.2.1 stdlib
- [x] Announce the releases
  - [x] Make both GitHub releases public
  - [x] Publish Blog Post on scala-lang.org
  - [x] Open the 3.2.2 tracking thread https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

**Comment by WojciechMazur** [comment]
Scala Native compiler plugins for 3.2.1 were released for versions 0.4.6 and 0.4.7

**Comment by som-snytt** [comment]
`sdkman` publication failed at https://github.com/lampepfl/dotty/actions/runs/3394041498/jobs/5642099256

**Comment by Kordyjan** [comment]
@som-snytt Thanks for pointing out the failed sdkman publication. The job is so unreliable, we should probably do something about it.
