### ISSUE TITLE
3.2.2-RC2 release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#16579]
- [x] Merge beckported prs:
  - [x] https://github.com/lampepfl/dotty/pull/16575
  - [x] https://github.com/lampepfl/dotty/pull/16576
  - [x] https://github.com/lampepfl/dotty/pull/16578
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.2.2` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.2.2-RC2`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.2.2-RC1`
    - [x] in `changelogs` add file with a changelog
    - [x] Tag the branch as `3.2.2-RC2`
- [x] On `main`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.2.2-RC2`
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Comment on the announcement thread on https://contributors.scala-lang.org

**Comment by SethTisue** [comment]
is this done?

**Comment by prolativ** [comment]
It seems so
