### ISSUE TITLE
3.2.2 & 3.3.0-RC2 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#16662]
- [x] Close the [3.2.2 backports milestone](https://github.com/lampepfl/dotty/milestone/45)
- [x] Publish 3.2.2 artifacts to Maven via CI
  - [x] On `release-3.2.2` branch
    - [x] In `Build.scala`: Set `baseVersion` to `3.2.2`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.2.1`
    - [x] In `changelogs` add file with a changelog
    - [x] Tag the branch as `3.2.2`
- [x] On `main` (https://github.com/lampepfl/dotty/pull/16671):
  - [x] In `Build.scala`: Set `previousDottyVersion` to `3.2.2`
  - [x] In `Build.scala`: Set `referenceVersion` to `3.2.2`
- [x] Close the [3.3.0-RC1 milestone](https://github.com/lampepfl/dotty/milestone/38)
- [x] Create the [`3.3.0 backports` milestone](https://github.com/lampepfl/dotty/milestone/48)
- [x] Publish 3.3.0-RC2 artifacts to Maven via CI
   - [x] On `release-3.3.0` branch:
     - [x] Fix the incorrect TASTy version
     - [x] In `changelogs` add file with a changelog
     - [x] Tag the branch as `3.3.0-RC2`
- [x] On `main`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.3.0-RC2`
  - [x] In `project/MiMaFilters.scala`: Remove all unnecessary `exclude` filters
  - [x] In `Build.scala`: Set `baseVersion` to `3.3.1-RC1`
  - [x] In `TastyFormat.scala`: Set TASTy version to `28.4-1`
- [x] Release ecosystem for 3.2.2
- [x] Wait for confirmation from tooling:
  - [x] Metals (@tgodzik)
  - [x] Scala CLI (@lwronski) 
  - [x] Scala Native (@WojciechMazur) 
  - [x] Scastie (@rochala) 
  - [x] Scala DAP (@adpi2) 
- [x] Release to SDKMAN
- [x] Merge `release-3.2.2` into `language-reference-stable`
- [x] Publish API docs for 3.2.2 stdlib
- [ ] Announce the releases
  - [x] Make both GitHub releases public
  - [ ] Publish Blog Post on dotty.epfl.ch
  - [x] Open the 3.3.0 tracking thread https://contributors.scala-lang.org

**Comment by julienrf** [comment]
May I ask you to include a PR to update scastie, in the release procedure? see scalacenter/scastie#660

**Comment by Kordyjan** [comment]
@julienrf this was what I meant by "Wait for confirmation from [...] Scastie". As we agreed with @rochala to just notify him when the new version should start being available. 
Of course I can make creating the PR as a part of the release scripts.

**Comment by julienrf** [comment]
Oh sorry I missed that “scastie” item in the list, nevermind! Thank you!

**Comment by adpi2** [comment]
Here is the release of [scala-expresion-compiler_3.2.2](https://repo1.maven.org/maven2/ch/epfl/scala/scala-expression-compiler_3.2.2/) needed by the scala-debug-adapter

**Comment by tgodzik** [comment]
`3.2.2` support is added for the latest metals and merged in main :tada: 

Let us know when the next RC is on maven

**Comment by WojciechMazur** [comment]
Scala Native compiler plugins for 3.2.2 are released for versions 0.4.6 .. 0.4.9 (latest)

**Comment by Kordyjan** [comment]
The whole release procedure has been on hold for a few days because we need to get https://github.com/lampepfl/dotty/pull/16612 right to release 3.3.0-RC1.

**Comment by Kordyjan** [comment]
Unfortunately, we have a problem with 3.3.0-RC1. It generates output with the wrong TASTy version. There will be RC2 later today.

**Comment by aisven** [comment]
Regarding Wikipedia and 3.2.2 etc.: the data in wikidata at https://www.wikidata.org/wiki/Q460584 which backs the Wikipedia page https://en.wikipedia.org/wiki/Scala_(programming_language) is somewhat outdated and should be updated.

(I tried to update this myself, but seems I have no permission editing without a user account over there.)

**Comment by SethTisue** [comment]
I'll assume it's inadvertent this ticket hasn't already been closed.

My understanding is that 3.3.0-RC4 is imminent (next week, perhaps?).
