### ISSUE TITLE
3.3.0-RC3 release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#16949]
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.3.0` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.3.0-RC3`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.3.0-RC2`
    - [x] in `changelogs` add file with a changelog
    - [x] Tag the branch as `3.3.0-RC3`
- [ ] On `main`:
  - [ ] In `Build.scala`: Set `referenceVersion` to `3.3.0-RC3`
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Comment on the announcement thread on https://contributors.scala-lang.org

**Comment by WojciechMazur** [comment]
There are **no new regressions** found in Open CB since 3.3.0-RC2

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Here's the list of all failing projects, when compared to Scala 3.2.2 - most of them is no longer source compatible: 
| Project | Version | Build URL | Notes |
| ------- | ------- | --------- | ----- |
| andyglow/typesafe-config-scala | 2.0.0 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7342034373) |  |
| argonaut-io/argonaut | 6.2.6 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7343763157) |  |
| babylonhealth/lit-fhir | 0.14.17 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7343763525) |  |
| dobrynya/zio-jms | 0.2 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7342930300) |  |
| giiita/refuel | 2.0.2 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7342037840) |  |
| gzoller/scalajack | 7.0.3 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7342038293) |  |
| itv/quartz4s | 1.0.4 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7346688330) |  |
| max-leuthaeuser/scroll | 3.0 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7340734439) |  |
| monix/monix-connect | 0.9.0 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7345479425) |  |
| ohze/akka-guice | 3.3.1 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7342042848) |  |
| ohze/couchbase-scala | 9.2.0 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7343967992) |  |
| ohze/sd-util | 1.3.0 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7343766670) |  |
| profunktor/neutron | 0.7.1 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7344298951) |  |
| reactivemongo/reactivemongo | 1.1.0-RC5 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7343569813) |  |
| rssh/dotty-cps-async | 0.9.14 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7340735381) |  |
| sangria-graphql/macro-visit | 0.2.0-RC1 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7342045309) |  |
| scala-ts/scala-ts | 0.5.15 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7340735825) |  |
| scalacenter/tasty-query | 0.5.7 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7342045941) |  |
| tinkoff/oolong | 0.1 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7346689248) |  |
| tinkoff/phobos | 0.19.2 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7344198476) |  |
| tomasmikula/nutcracker | 0.1.9 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7342937098) |  |
| virtuslab/avocado | 0.1.4 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7343769291) |  |
| y-yu/excel-reads | 0.4.2 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7344923026) |  |
| zio/caliban-deriving | 0.0.1 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7347387488) |  |
| zio/interop-cats | 23.0.0.1 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7344198941) |  |
| zio/zio-schema | 0.4.2 | [Open CB logs]() |  |
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Projects with last successful builds using Scala <b>with no successful builds data</b> [3]:
| Project | Version | Build URL | Notes |
| ------- | ------- | --------- | ----- |
| armanbilge/circe | 0.14.2-158-f15be0d | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7343071905) |  |
| circe/circe | 0.14.3 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7343072395) |  |
| wvlet/airframe | 23.1.1 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4226848191/jobs/7342050969) |  |
