### ISSUE TITLE
3.3.0-RC4 release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#17290]
- [ ] Publish artifacts to Maven via CI
  - [x] On `release-3.3.0` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.3.0-RC4`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.3.0-RC3`
    - [x] in `changelogs` add file with a changelog
    - [x] Tag the branch as `3.3.0-RC4`
- [x] On `main`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.3.0-RC4`
    https://github.com/lampepfl/dotty/pull/17307
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Comment on the announcement thread on https://contributors.scala-lang.org

**Comment by Kordyjan** [comment]
The build: https://github.com/lampepfl/dotty/actions/runs/4721339846

**Comment by Kordyjan** [comment]
Two fails due to coursier. I've included https://github.com/lampepfl/dotty/pull/17127 and rerun the build: https://github.com/lampepfl/dotty/actions/runs/4729732928
