### ISSUE TITLE
[Progress] - start utilizing `data` in diagnostics to forward  "quickfixes" to tools

### ISSUE THREAD

**Issue by ckipp01** [lampepfl/dotty#17337]
This is a follow-up to the work outlined in [this issue](https://github.com/lampepfl/dotty/issues/14904). While the work in that
issue focused around forwarding the `DiagnosticCode` and `DiagnosticRelatedInformation`, this issue is meant to track the work that is necessary to start utilizing the `data` field in the `Diagnostic` in order to forward quick fixes right from the compiler to your editor. Just to given an example, here a POC that was done during the Scala Tooling Summit showing a fix
coming from the compiler and being consumed from IntelliJ.

https://user-images.githubusercontent.com/13974112/234052622-19202314-1165-4b2c-91f9-2f66cf75e90d.mov

Like the other issue there are a fair amount of steps to start utilizing data in
this way. I've outlined the various steps below:

- [x] Agree on the format that these should have. We talked about this at the Tooling Summit and also in the summit repo afterwards. The format that seems to make the most sense is to put it under an `edits` key which contains and array of [`WorkspaceEdit`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceEdit)s. This structure is now also being utilized by tools like
  [scala-cli](https://github.com/VirtusLab/scala-cli/pull/1969) and other tools like [Metals](https://github.com/scalameta/metals/pull/5173) are ready to handle them. While this makes sense in BSP land, it's possible that it we could avoid some of the complexity that exists in the `WorkspaceEdit` and use a more minimal format in sbt-interface/compiler that later gets turned into a workspace edit later on.
  - Landed on a format that can be seen in [here](https://contributors.scala-lang.org/t/roadmap-for-actionable-diagnostics/6172/8?u=ckipp01)
- [x]  `data` (or whatever representation we have) needs to be added to [`Problem`](https://github.com/sbt/sbt/blob/1.9.x/internal/util-interface/src/main/java/xsbti/Problem.java) in sbt so that everything can use it.
  - https://github.com/sbt/sbt/pull/7242
- [x] Dotty will have to be update to use this new sbt interface when it's released.
  - https://github.com/lampepfl/dotty/pull/17561#issuecomment-1592979079
- [x] build tools will need to make sure to forward it via BSP
  - https://github.com/scalacenter/bloop/pull/2064
  - https://github.com/sbt/sbt/pull/7264
- [x]  We'll have to start utilizing the field to forward "quick fixes". 
  - https://github.com/scalameta/metals/pull/5338

Just to give a few examples, here are some candidates that came up during the discussions around this:

- implement all members
- add type for recursion automatically if possible
- auto import implicits
- add an import enabling a (experimental/compatibility/...) language feature - in some (most?) situations this could be alternatively achieved (globally rather than just in a single file) by adding a compiler option but this seems much more complicated as each build tool specifies compiler options in a different way and the compiler should be build tool agnostic
- add missing case clauses in a pattern match - E029
- remove redundant/disallowed keyword - E015, E037, E062, E063, E064, E065

I can update this as I get more details, but just creating this to start tracking progress on this.

**Comment by ckipp01** [comment]
Alright with the latest nightlies this now works when using the latest sbt and the latest Bloop version. I'll go ahead and close this for now with the hopes that more actions can be added than the initial 3 in #17561. We can also add feature requests in the Discussions for specific ones.
