### ISSUE TITLE
3.3.0-RC5 release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#17359]
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.3.0` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.3.0-RC5`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.3.0-RC4`
    - [x] in `changelogs` add a file with a changelog
    - [x] Tag the branch as `3.3.0-RC5`
- [x] On `main`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.3.0-RC5`
  https://github.com/lampepfl/dotty/pull/17365
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Comment on the announcement thread on https://contributors.scala-lang.org
