### ISSUE TITLE
3.3.0 & 3.3.1-RC1 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#17559]
- [x] Close the [3.3.0 backports milestone](https://github.com/lampepfl/dotty/milestone/48)
- [x] Publish 3.3.0 artifacts to Maven via CI
  - [x] On `release-3.3.0` branch
    - [x] In `Build.scala`: Set `baseVersion` to `3.3.0`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.2.2`
    - [x] Set the TASTy version to `28.3-0`
    - [x] In `changelogs` add file with a changelog
    - [x] Tag the branch as `3.3.0`
  - [Build](https://github.com/lampepfl/dotty/actions/runs/5056826491)
- [x] On `main`:
  - [x] In `Build.scala`: Set `previousDottyVersion` to `3.3.0`
  - [x] In `Build.scala`: Set `referenceVersion` to `3.3.0`
  - [x] Check and update `project/MiMaFilters.scala`
- [x] Publish 3.3.1-RC1 artifacts to Maven via CI
   - [x] Create branch `release-3.3.1` from `main`
   - [x] On `release-3.3.1` branch:
     - [x]  Set the TASTy version to `28.3-0`
     - [x] In `changelogs` add file with a changelog
     - [x] Tag the branch as `3.3.1-RC1`
   - [Build](https://github.com/lampepfl/dotty/actions/runs/5077582429)
- [x] On `main`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.3.1-RC1`
  - [x] In `Build.scala`: Set `baseVersion` to `3.3.2-RC1` (temporarily)
  - [x] Check and update `project/MiMaFilters.scala`
  - https://github.com/lampepfl/dotty/pull/17600
- [x] Wait for confirmation from tooling:
  - [x] Metals (@tgodzik):
    - [x] 3.3.0
    - [x] 3.3.1-RC1
  - [x] Scala CLI (@lwronski):
    - [x] 3.3.0
    - [x] 3.3.1-RC1
  - [x] Scala Native (@WojciechMazur) 
    - [x] 3.3.0
    - [x] 3.3.1-RC1
  - [x] Scastie (@rochala):
    - [x] 3.3.0
    - [x] 3.3.1-RC1
  - [x] Scala DAP (@adpi2) 
    - [x] 3.3.0
    - [x] 3.3.1-RC1
- [x] Update the ecosystem
  - [x] Release 3.3.0 to SDKMAN
  - [x] Enable Scala Steward updates: https://github.com/scala-steward-org/scala-steward/pull/3064
  - [x] Update the templates and example projects:
    - [x] [scala3-mill-example-project](https://github.com/scala/scala3-mill-example-project): https://github.com/scala/scala3-mill-example-project/pull/19
    - [x] [scala3-cross.g8](https://github.com/scala/scala3-cross.g8): https://github.com/scala/scala3-cross.g8/pull/75
    - [x] [scala3-staging.g8](https://github.com/scala/scala3-staging.g8): https://github.com/scala/scala3-staging.g8/pull/43
    - [x] [scala3-tasty-inspector.g8](https://github.com/scala/scala3-tasty-inspector.g8): https://github.com/scala/scala3-tasty-inspector.g8/pull/38
    - [x] [scala3.g8](https://github.com/scala/scala3.g8): https://github.com/scala/scala3.g8/pull/113
- [x] Prepare the documentation:
  - [x] Merge `release-3.3.0` into `language-reference-stable`: https://github.com/lampepfl/dotty/pull/17587
  - [x] Publish API docs for 3.3.0 stdlib
  - [x] Add 3.3.0 to version list in API docs
  - [x] Mark 3.3.0 as a default version for API docs
  - [x] Update [docs.scala-lang](https://github.com/scala/docs.scala-lang): https://github.com/scala/docs.scala-lang/pull/2826
- [x] Announce the releases
  - [x] Make both GitHub releases public
  - [x] Publish Blog Post on dotty.epfl.ch: https://github.com/scala/scala-lang/pull/1505
  - [x] Open the 3.3.1 tracking thread https://contributors.scala-lang.org

**Comment by Kordyjan** [comment]
Scala 3.3.0 is available on Maven Central.

pinging @tgodzik @lwronski  @WojciechMazur @rochala @adpi2

**Comment by WojciechMazur** [comment]
Scala Native compiler plugins for 3.3.0 are published for Scala Native 0.4.12.
We can expect a release 0.4.13 later this week. It would include `scalalib` based on Scala 3.3.0 - the current one is based on 3.2.2, which means the runtime would not include any changes made to stdlib.

**Comment by lwronski** [comment]
I confirm that the `scala-cli` works with Scala `3.3.0` and it will be the default version in the upcoming release - `1.0.0`.

**Comment by bishabosha** [comment]
> Merge `release-3.3.0` into `language-reference-stable`

- we should update docs to mention https://github.com/lampepfl/dotty/issues/17572
- also need to update http://dotty.epfl.ch/docs/reference/language-versions/source-compatibility.html to mention 3.3 mode

**Comment by Kordyjan** [comment]
Scala `3.3.1-RC1` is on Maven Central.

Pinging again: @WojciechMazur @tgodzik @lwronski @rochala @adpi2

**Comment by lwronski** [comment]
I confirm that the scala-cli works with Scala `3.3.1-RC1`

**Comment by ckipp01** [comment]
Is there anything left here? I see that all the tasks are ✅, so can this be closed?

**Comment by Kordyjan** [comment]
I should have automated the closing of the issues. 😅
