### ISSUE TITLE
3.3.1-RC2 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#18087]
- [x] Backport relevant fixes:
  - [x] https://github.com/lampepfl/dotty/pull/17615
    - https://github.com/lampepfl/dotty/pull/17749 
  - [x]  https://github.com/lampepfl/dotty/pull/18057
    - https://github.com/lampepfl/dotty/pull/18088
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.3.1` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.3.1-RC2`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.3.1-RC1`
    - [x] in `changelogs` add file with a changelog
    - [x] Tag the branch as `3.3.1-RC2`
  - https://github.com/lampepfl/dotty/actions/runs/5401953891
- [x] On `main`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.3.1-RC2`
  - https://github.com/lampepfl/dotty/pull/18146
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Comment on the announcement thread on https://contributors.scala-lang.org
