### ISSUE TITLE
3.3.1-RC3 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#18147]
- [x] Backport relevant fix:
  - [x] https://github.com/lampepfl/dotty/pull/18134
    - https://github.com/lampepfl/dotty/pull/18148
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.3.1` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.3.1-RC3`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.3.1-RC2`
    - [x] in `changelogs` add file with a changelog
    - [x] Tag the branch as `3.3.1-RC3`
- [x] On `main`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.3.1-RC3`
  - https://github.com/lampepfl/dotty/pull/18154
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Comment on the announcement thread on https://contributors.scala-lang.org

**Comment by He-Pin** [comment]
@Kordyjan Hi I'm wondering how do you keep track which commit/pr need to be back-ported to 3.3.x from master?

**Comment by Kordyjan** [comment]
>I'm wondering how do you keep track which commit/pr need to be back-ported to 3.3.x from master?

I'm just tracking [`backport:nominated`](https://github.com/lampepfl/dotty/pulls?q=is%3Apr+%60backport%3Anominated%60) and [`backport:accepted`](https://github.com/lampepfl/dotty/pulls?q=is%3Apr+label%3Abackport%3Aaccepted+) labels.
