### ISSUE TITLE
3.3.1-RC5 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#18373]
- [x] Backport relevant fixes:
  - [x] https://github.com/lampepfl/dotty/pull/18239:
    - https://github.com/lampepfl/dotty/pull/18328
  - [x] https://github.com/lampepfl/dotty/pull/18286:
    - https://github.com/lampepfl/dotty/pull/18329
  - [x] https://github.com/lampepfl/dotty/pull/18232:
    - https://github.com/lampepfl/dotty/pull/18330
  - [x] https://github.com/lampepfl/dotty/pull/18352:
    - https://github.com/lampepfl/dotty/pull/18371
  - [x] https://github.com/lampepfl/dotty/pull/18269:
    - ~https://github.com/lampepfl/dotty/pull/18372~
    - https://github.com/lampepfl/dotty/pull/18378
  - [x] (optionally) https://github.com/lampepfl/dotty/pull/18303:
    - https://github.com/lampepfl/dotty/pull/18374
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.3.1` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.3.1-RC5`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.3.1-RC4`
    - [x] in `changelogs` add file with a changelog
    - [x] Tag the branch as `3.3.1-RC5`
  - https://github.com/lampepfl/dotty/actions/runs/5818162051
- [x] On `main`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.3.1-RC5`
  - https://github.com/lampepfl/dotty/pull/18382
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Comment on the announcement thread on https://contributors.scala-lang.org

**Comment by soronpo** [comment]
What is the policy regarding fixing known regressions before issuing yet another RC?

**Comment by He-Pin** [comment]
So no features will be developed directly on 3.3.x but backpacking ？

**Comment by Kordyjan** [comment]
@soronpo: We intend to fix everything that is a regression compared to any released version of the current LTS line (currently only 3.3.0). We do not prioritize fixing things that appeared in the versions before 3.3.0. What's more, in case fixing some regression from, let's say, 3.2.1, breaks any library build for 3.3, we are not backporting that fix to the LTS.

The list for this RC was prepared a few weeks ago. In the meantime, 400 new projects appeared in the Open CB. Based on them we can suspect that we have two more regressions to deal with. We will investigate. This may result in 3.3.1-RC6.

**Comment by soronpo** [comment]
I found #18253 that started in 3.3.1-RCX
I also found another regression in 3.3.2-RCX, but it may appear in 3.3.1 depending on what is backported.

**Comment by soronpo** [comment]
> I found #18253 that started in 3.3.1-RCX

Oops, my mistake, it was 3.1.2-RCX

**Comment by soronpo** [comment]
OK, now I see why I made the mistake. A change in 3.3.x caused this bug to appear.
@Kordyjan, what do you do in the following cases? I have a working code in 3.3.0 LTS, but changes in 3.3.1 caused two bugs. While trying to minimize those bugs, I found they were actually earlier regressions that were somehow masked under LTS. So for all intent and purpose, these regressions affect the LTS release, no? We won't be going back and reverting a compiler change that exposed those earlier bugs, right?
The issues I'm referring to are #18253 and #18263

**Comment by Kordyjan** [comment]
Which case was that? Did some change in 3.3.1-RCx force you to change your code, and you bumped into something that should have been working and was working in previous versions but now doesn't? Or did the code just stop compiling after changing from 3.3.0 to 3.3.1-RCx, and then the minimization discovered some other (possibly related bug)?

In the first case, the thing that forced you to change the code is a regression; we will fix it when we learn more about it. In the second case this is either unrelated bug found during the minimization or the situation where two other bugs countered each other perfectly, and one of them were fixed. If this is the case we will either need to fix both of the issues or reintroduce the fixed bug to preserve compatibility.

**Comment by soronpo** [comment]
My library compiled successfully under 3.3.0 (LTS). It fails to compile under 3.3.1-RCx. After minimizing the bugs (https://github.com/lampepfl/dotty/issues/18253 and https://github.com/lampepfl/dotty/issues/18263), the minimization also fails to work on earlier scalac versions. Somehow these bugs were canceled by some other compiler issues that was since resolved.

**Comment by soronpo** [comment]
Another thing, why was  #18214 not backported? It fixes a regression from 3.3.0, but it marked for 3.4.x.

**Comment by Kordyjan** [comment]
This being in the 3.4.0 milestone, only means that it is not backported yet, not that it will not be backported before the next RC.
