### ISSUE TITLE
3.3.1-RC6 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#18439]
- [x] Backport relevant fixes:
  - [x] https://github.com/lampepfl/dotty/pull/18204 
	- https://github.com/lampepfl/dotty/pull/18410
  - [x] https://github.com/lampepfl/dotty/pull/18288 
	- https://github.com/lampepfl/dotty/pull/18411
  - [x] revert https://github.com/lampepfl/dotty/pull/17457
    - https://github.com/lampepfl/dotty/pull/18440  
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.3.1` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.3.1-RC6`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.3.1-RC5`
    - [x] in `changelogs` add file with a changelog
    - [x] Tag the branch as `3.3.1-RC6`
  - https://github.com/lampepfl/dotty/actions/runs/5938113818
- [x] On `main`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.3.1-RC6`
  - https://github.com/lampepfl/dotty/pull/18471
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Comment on the announcement thread on https://contributors.scala-lang.org
