### ISSUE TITLE
3.3.1-RC7 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#18474]
- [x] Backport relevant fixes:
  - [x] https://github.com/lampepfl/dotty/pull/18467
    - https://github.com/lampepfl/dotty/pull/18475
  - [x] revert https://github.com/lampepfl/dotty/pull/16849
    - https://github.com/lampepfl/dotty/pull/18473  
- [x] Publish artifacts to Maven via CI
  - [x] On `release-3.3.1` branch:
    - [x] In `Build.scala`: Set `baseVersion` to `3.3.1-RC7`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.3.1-RC6`
    - [x] in `changelogs` add file with a changelog
    - [x] Tag the branch as `3.3.1-RC7`
  - https://github.com/lampepfl/dotty/actions/runs/6014684444
- [x] On `main`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.3.1-RC7`
  - https://github.com/lampepfl/dotty/pull/18483
- [x] Announce the release
  - [x] Publish release on GitHub Releases
  - [x] Comment on the announcement thread on https://contributors.scala-lang.org
