### ISSUE TITLE
3.3.1 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#18515]
- [x] Close the [3.3.1 milestone](https://github.com/lampepfl/dotty/milestone/47)
- [x] Publish 3.3.1 artifacts to Maven via CI
  - [x] On `release-3.3.1` branch
    - [x] In `Build.scala`: Set `baseVersion` to `3.3.1`
    - [x] In `Build.scala`: Set `previousDottyVersion` to `3.3.0`
    - [x] In `changelogs` add file with a changelog
    - [x] Tag the branch as `3.3.1`
  - https://github.com/lampepfl/dotty/actions/runs/6084672111
- [x] On `main`:
  - [x] In `Build.scala`: Set `previousDottyVersion` to `3.3.1`
  - [x] In `Build.scala`: Set `referenceVersion` to `3.3.1`
  - [x] Check and update `project/MiMaFilters.scala`
  - https://github.com/lampepfl/dotty/pull/18585
- [x] Wait for confirmation from tooling:
  - [x] Metals (@tgodzik):
  - [x] Scala CLI (@tgodzik):
  - [x] Scala Native (@WojciechMazur) 
  - [x] Scastie (@rochala):
  - [x] Scala DAP (@adpi2) 
- [x] Update the ecosystem
  - [x] Release 3.3.1 to SDKMAN
  - [x] Enable Scala Steward updates:
    - https://github.com/scala-steward-org/scala-steward/pull/3159
  - [x] Update the templates and example projects:
    - [x] [scala3-mill-example-project](https://github.com/scala/scala3-mill-example-project):
      - https://github.com/scala/scala3-mill-example-project/pull/21
    - [x] [scala3-cross.g8](https://github.com/scala/scala3-cross.g8):
       - https://github.com/scala/scala3-cross.g8/pull/85
    - [x] [scala3-staging.g8](https://github.com/scala/scala3-staging.g8):
       - https://github.com/scala/scala3-staging.g8/pull/44
    - [x] [scala3-tasty-inspector.g8](https://github.com/scala/scala3-tasty-inspector.g8): 
      - https://github.com/scala/scala3-tasty-inspector.g8/pull/39
    - [x] [scala3.g8](https://github.com/scala/scala3.g8):
      - https://github.com/scala/scala3.g8/pull/123
- [x] Prepare the documentation:
  - [x] Merge `release-3.3.1` into `language-reference-stable`
  - [x] Publish API docs for 3.3.1 stdlib
  - [x] Add 3.3.1 to version list in API docs
  - [x] Mark 3.3.1 as a default version for API docs
  - [x] Update [docs.scala-lang](https://github.com/scala/docs.scala-lang):
    - https://github.com/scala/docs.scala-lang/pull/2899
- [x] Announce the releases
  - [x] MakeGitHub release public
  - [x] Publish Blog Post on scala-lang.org: https://github.com/scala/scala-lang/pull/1545
  - [x] Update the 3.3.1 release thread: https://contributors.scala-lang.org/t/3-3-1-release-thread/6208

**Comment by Kordyjan** [comment]
The artifacts are on maven central.

**Comment by WojciechMazur** [comment]
Compiler plugins for Scala Native 0.4.14 and 0.4.15 are published for Scala 3.3.1

**Comment by adpi2** [comment]
Expression compiler (DAP) 3.1.3 and 3.1.4 published for Scala 3.3.1

**Comment by tgodzik** [comment]
Metals 1.0.1 published for Scala 3.3.1 :tada:  Working on merging to snapshots

**Comment by spamegg1** [comment]
3.3.1 is still not available on SDKMAN, I asked the developer and he said something probably went wrong: https://github.com/sdkman/sdkman-cli/discussions/1237#discussioncomment-7030639

**Comment by marc0der** [comment]
@Kordyjan I believe that calling the SDKMAN vendor API is part of your manual release process. Just wanted to check if something went wrong. Please give me a shout if you need my help or if something on our end isn't working as expected.

**Comment by som-snytt** [comment]
Also https://discord.com/channels/632150470000902164/632628489719382036/1151677972005269524

I remember there was a previous lapse. This time, I wasn't sure if sdkman had been downgraded as a priority because of scala-cli.

**Comment by marc0der** [comment]
I've just published version 3.3.1 and set it as default. Please give me a shout if you have any issues with our API in the future @Kordyjan.

**Comment by Kordyjan** [comment]
@marc0der Thank you for publishing.

I've just checked and it seems that the problem was caused by a bug in our release script. It couldn't find artifacts for the version it should publish but nevertheless returned a success.

**Comment by marc0der** [comment]
Great, thanks for the update @Kordyjan.
