### ISSUE TITLE
3.3.2-RC1 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#19276]
- [x] Publish 3.3.2-RC1 artifacts to Maven via CI
   - [x] On `release-3.3.2` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] Tag the branch as `3.3.2-RC1`
     - [Build](https://github.com/lampepfl/dotty/actions/runs/7224862564)
- [x] Wait for confirmation from tooling:
  - [x] Metals (@tgodzik):
    - https://github.com/scalameta/metals/pull/5958
  - [x] Scala CLI (@tgodzik)
  - [x] Scala Native (@WojciechMazur) 
  - [x] Scastie (@rochala)
  - [x] Scala DAP (@adpi2) 
- [x] Announce the releases
  - [x] Make GitHub releases public
  - [x] Open the 3.3.2 tracking thread https://contributors.scala-lang.org
