### ISSUE TITLE
3.4.0-RC1 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#19312]
- [x] Publish 3.4.0-RC1 artifacts to Maven via CI
   - [x] On `release-3.4.0` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] Tag the branch as `3.4.0-RC1`
     - [Build](https://github.com/lampepfl/dotty/actions/runs/7278224772)
- [x] Wait for confirmation from tooling:
  - [x] Metals (@tgodzik)
  - [x] Scala CLI (@tgodzik)
  - [x] Scala Native (@WojciechMazur)
  - [x] Scastie (@rochala)
  - [x] Scala DAP (@adpi2)
- [ ] On `main`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.4.0-RC1`
  - [x] In `Build.scala`: Set `baseVersion` to `3.4.1-RC1`
  - [x] Check and update `project/MiMaFilters.scala`
  - [x] In TastyFormat.scala: Set TASTy version to 28.5-1
  - https://github.com/lampepfl/dotty/pull/19321
- [x] Announce the releases
  - [x] Make GitHub releases public
  - [x] Open the 3.4.0 tracking thread https://contributors.scala-lang.org

**Comment by Kordyjan** [comment]
Artifacts are published on Maven Central!

**Comment by adpi2** [comment]
I cannot release the current expression compiler on 3.4.0-RC1 because of some changes in the compiler API. I'll fix it in a future version of the scala-debug-adapter. You can ignore me for now.

**Comment by WojciechMazur** [comment]
Scala Native would require a new release due to changes in compiler API used in the plugin (https://github.com/WojciechMazur/scala-native/commit/26235e7f6581729ee477eb1c8e430ec8727ef6c6) 
I'm still fixing the build to test runtime when compiled with 3.4.0-RC1

**Comment by WojciechMazur** [comment]
We've found a typer regression when testing Scala Native, probably RC2 would be required. Same regression is present in 3.3.2-RC1. https://github.com/lampepfl/dotty/issues/19324
