### ISSUE TITLE
3.4.0-RC2 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#19487]
- [x] Publish 3.4.0-RC2 artifacts to Maven via CI
   - [x] On `release-3.4.0` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] In `Build.scala`: Set `baseVersion` to `3.4.0-RC2`
     - [x] In `Build.scala`: Set `previousDottyVersion` to `3.4.0-RC1`
     - [x] Tag the branch as `3.4.0-RC2`
     - [Build](https://github.com/lampepfl/dotty/actions/runs/7583635349)
- [x] Wait for confirmation from tooling:
  - [x] Metals (@tgodzik)
  - [x] Scala CLI (@Gedochao)
  - [x] Scala Native (@WojciechMazur)
  - [x] Scastie (@rochala)
  - [x] Scala DAP (@adpi2)
- [x] Announce the releases
  - [x] Make GitHub releases public
  - [x] Update the [3.4.0 tracking thread](https://contributors.scala-lang.org/t/3-4-0-release-thread/6445)

**Comment by nicolasstucki** [comment]
It seems we are releasing `3.4.0-RC2` with the experimental tag `1` https://github.com/lampepfl/dotty/blob/6dfb1b5eee1fc46fb9bdc1efd49ce359c09778bc/tasty/src/dotty/tools/tasty/TastyFormat.scala#L337

This does not seem to align with https://github.com/lampepfl/dotty/pull/19321#discussion_r1458730048. This seems to indicate we need experimental tag `2` for this release. @bishabosha did I interpret this correctly?

**Comment by nicolasstucki** [comment]
The concern is that `3.4.0-RC1` had the wrong TASTy experimental version. And this one should have the same one. This is not critical, but it would imply that we will only be able to use `3.4.0` as a reference compiler and not `3.4.0-RC2`.

**Comment by Kordyjan** [comment]
Yes, that's true, but I cannot see why 28.4-2 instead of 28.4-1 would make any difference, as the tasty version on nightly should be 28.5-1, which is incompatible with both of them.

**Comment by nicolasstucki** [comment]
We could have an extra rule in the version checks to allow `-2` in this situation. Not sure what was the original plan with that version.

**Comment by Kordyjan** [comment]
It may have been somehow related to the planned and later scrapped `--scala-output-version,` which was being developed around that time. I'm ok with bringing back `-2` versions before 3.5.0.

**Comment by bishabosha** [comment]
the `-2` would only be significant if we care about breaking compatibility between 3.3.x nightlies and `3.4.0-RC2`, which is a noble goal but maybe not critical

**Comment by Kordyjan** [comment]
Artifacts for 3.4.0-RC2 are on maven central.

**Comment by tgodzik** [comment]
Works with Metals :tada:

**Comment by nicolasstucki** [comment]
An issue was found with the definitions of `` scala.language.`3.5` `` in  https://github.com/lampepfl/dotty/pull/19503.

**Comment by Kordyjan** [comment]
> An issue was found with the definitions of `` scala.language.`3.5` `` in #19503.

I must admit that I thought that ``scala.language.`3.5` `` should only be added in 3.5.0, and before that, things that will no longer work in 3.5 are marked as not working in `scala.language.future`.

**Comment by Kordyjan** [comment]
Somehow, I haven't thought about it as already merged to the main. Indeed, if it is intended to be released in 3.4.1, we need this symbol in 3.4.0.

**Comment by Kordyjan** [comment]
I started the process for 3.4.0-RC3:
https://github.com/lampepfl/dotty/issues/19517

**Comment by adpi2** [comment]
I am done with the release of DAP for 3.4.0-RC2: https://repo1.maven.org/maven2/ch/epfl/scala/scala-expression-compiler_3.4.0-RC2/
