### ISSUE TITLE
3.4.0-RC3 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#19517]
- [x] Merge #19515
- [x] Backport #19512
  - [x] #19518
- [x] Publish 3.4.0-RC3 artifacts to Maven via CI
   - [x] On `release-3.4.0` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] In `Build.scala`: Set `baseVersion` to `3.4.0-RC3`
     - [x] In `Build.scala`: Set `previousDottyVersion` to `3.4.0-RC3`
     - [x] Tag the branch as `3.4.0-RC3`
     - [Build](https://github.com/lampepfl/dotty/actions/runs/7643009463)
- [x] Wait for confirmation from tooling:
  - [x] Metals (@tgodzik)
  - [x] Scala CLI
  - [x] Scala Native (@WojciechMazur)
  - [x] Scastie (@rochala)
  - [x] Scala DAP 
- [x] On `main`:
  - [x] In `Build.scala`: Set `referenceVersion` to `3.4.0-RC3`
  - [x] Check and update `project/MiMaFilters.scala`
- [x] Announce the releases
  - [x] Make GitHub releases public
  - [x] Update the [3.4.0 tracking thread](https://contributors.scala-lang.org/t/3-4-0-release-thread/6445)

**Comment by Kordyjan** [comment]
The artifacts are on maven central.

**Comment by tgodzik** [comment]
Metals works ok with 3.4.0-RC3
