### ISSUE TITLE
3.3.2-RC2 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#19573]
- [x] Publish 3.3.2-RC2 artifacts to Maven via CI
   - [x] On `release-3.3.2` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] In `Build.scala`: Set `baseVersion` to `3.3.2-RC2`
     - [x] In `Build.scala`: Set `previousDottyVersion` to `3.3.2-RC1`
     - [x] Tag the branch as `3.3.2-RC2`
   - [Build](https://github.com/lampepfl/dotty/actions/runs/7729020153)
- [x] Wait for confirmation from tooling:
  - [x] Metals (@tgodzik) 
  - [x] Scala CLI
  - [x] Scala Native (@WojciechMazur)
  - [x] Scastie(@rochala)
  - [x] Scala DAP (@adpi2)
- [x] Announce the releases
  - [x] Make GitHub releases public
  - [x] Update the [3.3.2 tracking thread](https://contributors.scala-lang.org/t/3-3-2-release-thread/6433)
