### ISSUE TITLE
3.3.2 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#19682]
### Publish 3.3.2 artifacts to Maven Central via CI:
- [x] On `release-3.3.2` branch:
  - [x] In `Build.scala`: Set `baseVersion` to `3.3.2`
  - [x] In `Build.scala`: Set `referenceVersion` to `3.3.1`
  - [x] In `changelogs` add file with a changelog
- [x] Tag the branch as `3.3.2`
- [Build](https://github.com/lampepfl/dotty/actions/runs/7900749934) 
 
### Confirm that the tooling is working correctly:
- [x] Metals (@tgodzik)
- [x] Scala CLI
- [x] Scala Native
- [x] Scastie
- [x] Scala DAP (@adpi2)

### Update the ecosystem:
- [ ] Release 3.3.2 to SDKMAN

### Prepare the documentation:
- [ ] Merge `release-3.3.2` into `language-reference-stable`
- [x] Publish API docs for 3.3.2
- [x] Add 3.3.2 to the version list in API docs
- [ ] Update [docs.scala-lang](https://github.com/scala/docs.scala-lang)

### Announce the releases:
- [ ] Make GitHub release public
- [ ] Publish a post on https://scala-lang.org/blog
- [x] Close the 3.2.2 milestone

**Comment by insiddius** [comment]
Actively watching this! Is there an updated ETA?

**Comment by sjrd** [comment]
:warning: We might have to bankrupt 3.3.2: https://github.com/playframework/playframework/issues/12418

It produces .tasty files that cannot be read by 3.3.0 and 3.3.1.

**Comment by mkurz** [comment]
> ⚠️ We might have to bankrupt 3.3.2: [playframework/playframework#12418]

_If_ you do so, I recommend opening a pull request to make Scala Steward ignore the 3.3.2 release so it stops opening pull requests to upgrade projects, just like I did back a couple of months ago with Play 2.9.0-RC1: https://github.com/scala-steward-org/scala-steward/commit/15ad2e2359a85cafb0a48f52e8566a2cd1518cd4

**Comment by sjrd** [comment]
We do that *by default*:
https://github.com/scala-steward-org/scala-steward/blob/9a8f6d3ab4927ea8a07cbd91cc8e1de44090654d/modules/core/src/main/resources/default.scala-steward.conf#L33-L39
We tell Scala Steward to *allow* the upgrades to 3.3.2 only after all the release steps are over.

**Comment by mkurz** [comment]
> We tell Scala Steward to _allow_ the upgrades to 3.3.2 only after all the release steps are over.

Ah nice! Didn't know that :+1:

**Comment by Kordyjan** [comment]
[3.3.3 hotfix Procedure](https://github.com/lampepfl/dotty/issues/19820)
