### ISSUE TITLE
3.3.3 LTS Hotfix release procedure

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#19820]
- [x] Wait for the open community build runs results ([1](https://github.com/VirtusLab/community-build3/actions/runs/8081092060), [2](https://github.com/VirtusLab/community-build3/actions/runs/8081101000), [3](https://github.com/VirtusLab/community-build3/actions/runs/8081108020) and [4](https://github.com/VirtusLab/community-build3/actions/runs/8081114437))
- [x] Merge #19818
- [x] Tag the release commit with `3.3.3`
- [Build](https://github.com/lampepfl/dotty/actions/runs/8093903970)
- [x] Wait for the confirmation from the tooling maintainers:
   - [x] Metals (@tgodzik)
   - [x] Scala DAP (@adpi2)
   - [x] Scastie (@rochala)
   - [x] Scala Native (@WojciechMazur)
   - [x] Scala CLI (@Gedochao)
- [x] Publish API docs for 3.3.3
- [x] Add 3.3.3 to the version list in API docs
- [x] Update [docs.scala-lang](https://github.com/scala/docs.scala-lang)
- [x] Make GitHub release public
- [x] Announce the release (https://github.com/scala/scala-lang/pull/1598#pullrequestreview-1906239097)

**Comment by Kordyjan** [comment]
Artifacts are available on maven central.

**Comment by mkurz** [comment]
SDKMAN is missing 3.3.3, but 3.4.0 is available (maybe you are aware of that anyway, just want to mention it because this issue was closed):
```
$ sdk upgrade scala && sdk list scala

scala is up-to-date
================================================================================
Available Scala Versions
================================================================================
   * 3.4.0               2.13.9              2.12.12             2.11.6         
 > * 3.3.1               2.13.8              2.12.11             2.11.5     
....
```

**Comment by Kordyjan** [comment]
@mkurz 3.3.3 is now present on sdkman.
