### ISSUE TITLE
Meta-issue: Port Backend improvements

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3113]
- [x] Port https://github.com/scala/scala/pull/4963
- [x] scala/scala#6070
- [x] [Desugar string concat to java.lang.StringBuilder](https://github.com/scala/scala/pull/4737) (https://github.com/lampepfl/scala/pull/27)
- [x] [Avoid boxing primitives in string concatenation](https://github.com/scala/scala/pull/4944) (https://github.com/lampepfl/scala/pull/27)
- [x] [upgrade asm to 5.1](https://github.com/scala/scala/pull/5293) -- (https://github.com/lampepfl/scala/pull/24)
- [x] [Restrict library and reflect to compact1 profile](https://github.com/scala/scala/pull/6164)
- [x] [Add bridges for overridden methods in lambda indy call](https://github.com/scala/scala/pull/6087)
   - Maybe shouldn't be fixed in backend (["Perhaps this could be revisited for 2.13, which would simplify things for SJS (it wouldn't be a backend change anymore)"](https://github.com/scala/scala/pull/6087#issuecomment-330585723))
   - Ended up being done in erasure, see Erasure#typedClosure
- [ ] [Compiler crash in GenBCode referring to a class that extends an annotation](https://github.com/lampepfl/dotty/issues/3403)
  - Maybe shouldn't be fixed in backend (["I'm fine with the approach of repairing this in the backend for now, but agree that a special case in the typer would be worth trying."](https://github.com/scala/scala/pull/4638#issuecomment-122153586))
- [x] [Fix code gen with returns in nested try-finally blocks](https://github.com/scala/scala/pull/5509)
- [ ] [ Don't emit forwarder in mirror class for bridge methods](https://github.com/scala/scala/pull/6531)
  - We should also consider whether we can emit static forwarders before the backend (["This looks rather difficult to fix with the way forwarders are currently done. I think the better solution would be to generate static forwarders earlier in the pipeline and have them transformed normally."](https://github.com/scala/bug/issues/5289#issuecomment-292400867))

**Comment by nicolasstucki** [comment]
@smarter, could you add the one you know should be ported.

**Comment by allanrenucci** [comment]
Maybe scala/scala#6012 ?

**Comment by smarter** [comment]
> https://github.com/scala/scala/pull/6012

I would rather not port refactorings, it would be a lot of work for not much benefit right now. Longer term we'll have to find some way to synchronize our backend with the scalac one, but right now we should only port simple things I think.

Here are the PRs I had in my TODO list to port:
- [Desugar string concat to java.lang.StringBuilder](https://github.com/scala/scala/pull/4737)
- [Avoid boxing primitives in string concatenation](https://github.com/scala/scala/pull/4944)
- [upgrade asm to 5.1](https://github.com/scala/scala/pull/5293)

**Comment by allanrenucci** [comment]
Dmitry ported scala/scala#4737 and reverted it: https://github.com/lampepfl/scala/commit/ccbac2472692ba89bdcbbebce1409c20ea791082

**Comment by allanrenucci** [comment]
Also we are already using `asm` version `5.1.0-scala-2`

**Comment by smarter** [comment]
> Dmitry ported scala/scala#4737 and reverted it: lampepfl/scala@ccbac24

Let's try doing it again and see if something breaks :)

> Also we are already using asm version 5.1.0-scala-2

Yes but the PR also updates the backend to not use deprecated methods, something we haven't done yet.

**Comment by smarter** [comment]
> Yes but the PR also updates the backend to not use deprecated methods, something we haven't done yet.

In fact, the PR does more than that, it fixes an issue preventing the emitted code from running under Java 9 (this is mentioned in https://github.com/scala/scala/pull/5452)

**Comment by smarter** [comment]
Still a WIP but we should keep an eye on https://github.com/scala/scala/pull/6087, the bug also affects Dotty.

**Comment by smarter** [comment]
I've opened https://github.com/lampepfl/dotty/issues/3403 to track another possible PR to port.

**Comment by nicolasstucki** [comment]
Please add the issues also to the list in the description

**Comment by smarter** [comment]
Added [Remove compiler dependency on @remote](https://github.com/scala/scala/pull/6164) to the list, this one should be easy to port.

**Comment by smarter** [comment]
Superceded by https://github.com/lampepfl/dotty/issues/14912
