### ISSUE TITLE
Compiling pos and run tests from TASTY

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3594]
These are the tests that still fail from tasty. Several of these tests fail due to same issues (will classify them later). This list was added as tests in #3593 which allows easy reproduction of the issues.

- [ ] tests/pos/Meter.scala
- [ ] tests/pos/NoCyclicReference.scala (issue #3816)
- [ ] tests/pos/depfuntype.scala
- [ ] tests/pos/hklub0.scala
- [ ] tests/pos/i0306.scala (issue #3500)
- [ ] tests/pos/i1365.scala (issue #3500)
- [ ] tests/pos/i1795.scala (issue #3816)
- [ ] tests/pos/i2345.scala
- [ ] tests/pos/i2888.scala (issue #3817)
- [ ] tests/pos/i2944.scala (issue #3500)
- [ ] tests/pos/i2980.scala
- [ ] tests/pos/i3000.scala
- [ ] tests/pos/i536.scala
- [ ] tests/pos/i974.scala (issue #3817)
- [ ] tests/pos/liftable.scala
- [ ] tests/pos/quoteTest.scala
- [ ] tests/pos/quoted.scala
- [ ] tests/pos/stagedInterpreter.scala
- [ ] tests/pos/superacc.scala
- [ ] tests/pos/t0231.scala
- [ ] tests/pos/t1203a.scala
- [ ] tests/pos/t2260.scala
- [ ] tests/pos/t3612.scala
- [ ] tests/pos/t3800.scala
- [ ] tests/pos/t4579.scala
- [ ] tests/pos/t8023.scala (issue #3500?)
- [ ] tests/pos/tcpoly_ticket2096.scala
- [ ] tests/pos/t247.scala
- [ ] tests/run/Course-2002-13.scala
- [ ] tests/run/NestedClasses.scala
- [ ] tests/run/bridges.scala
- [ ] tests/run/eff-dependent.scala
- [ ] tests/run/enum-approx.scala
- [ ] tests/run/i2337.scala
- [ ] tests/run/i2337b.scala
- [ ] tests/run/inlineForeach.scala
- [ ] tests/run/patmat-bind-typed.scala (issue #3500?)
- [ ] tests/run/phantom-decls-1.scala
- [ ] tests/run/phantom-decls-3.scala
- [ ] tests/run/phantom-decls-5.scala
- [ ] tests/run/phantom-hk-1.scala
- [ ] tests/run/phantom-hk-2.scala
- [ ] tests/run/phantom-in-value-class.scala
- [ ] tests/run/phantom-methods-3.scala
- [ ] tests/run/phantom-methods-4.scala
- [ ] tests/run/phantom-poly-1.scala
- [ ] tests/run/phantom-poly-2.scala
- [ ] tests/run/phantom-poly-3.scala
- [ ] tests/run/phantom-poly-4.scala
- [ ] tests/run/scala2trait-lazyval.scala
- [ ] tests/run/t3452f.scala
- [ ] tests/run/t493.scala
- [ ] tests/run/t8395.scala
- [ ] tests/run/t3613.scala
- [x] tests/pos/companions.scala
- [x] tests/pos/i1570.scala (issue #3597)
- [x] tests/pos/i1756.scala (issue #3596)
- [x] tests/pos/i1812.scala
- [x] tests/pos/i1812b.scala
- [x] tests/pos/i1990.scala (issue #3608)
- [x] tests/pos/i1990a.scala (issue #3608)
- [x] tests/pos/i2250.scala (issue #3598)
- [x] tests/pos/i2300.scala
- [x] tests/pos/i2397.scala (issue  #3598)
- [x] tests/pos/i2468.scala (issue #3462)
- [x] tests/pos/i3129.scala
- [x] tests/pos/i3130a.scala (issue #3608)
- [x] tests/pos/i3130d.scala (issue #3608)
- [x] tests/pos/i966.scala
- [x] tests/pos/i996.scala (issue #3598?)
- [x] tests/pos/supercalls.scala
- [x] tests/pos/t0049.scala (issue #3596)
- [x] tests/pos/t0055.scala (issue #3596)
- [x] tests/pos/t115.scala (issue #3596)
- [x] tests/pos/t1279a.scala
- [x] tests/pos/t1957.scala
- [x] tests/pos/t2127.scala (issue #3596)
- [x] tests/pos/t2405.scala (issue #3607)
- [x] tests/run/array-addition.scala
- [x] tests/run/i1569.scala (issue #3597)
- [x] tests/run/i1990b.scala
- [x] tests/run/i2163.scala
- [x] tests/run/inlinedAssign.scala
- [x] tests/run/t1909c.scala (issue #3596)
- [x] tests/run/t2127.scala (issue #3596)
- [x] tests/run/t3048.scala (issue #3596)
- [x] tests/run/t6506.scala (issue #3596)
- [x] tests/run/t6666a.scala
- [x] tests/run/t6957.scala (issue #3596)
- [x] tests/run/t8002.scala
- [x] tests/run/view-iterator-stream.scala

**Comment by nicolasstucki** [comment]
We had a few regressions since I listed them first, #3693 will ensure this does not happen again.

**Comment by nicolasstucki** [comment]
This list is now maintained in `dotty.tools.dotc.FromTastyTests`. Will close the issue as it is too hard to keep in sync.
