### ISSUE TITLE
Sbt 1 Migration

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4303]
## Community Build
- [x] [algebra](https://github.com/dotty-staging/algebra)
- [x] [better-files](https://github.com/dotty-staging/better-files)
- [x] [scalacheck](https://github.com/dotty-staging/scalacheck/tree/dotty)
- [x] [ScalaPB](https://github.com/dotty-staging/ScalaPB/tree/dotty)
- [x] [scalatest](https://github.com/dotty-staging/scalatest/tree/dotty)
- [x] [scopt](https://github.com/dotty-staging/scopt)
- [x] [squants](https://github.com/dotty-staging/squants)
- [x] [collections-strawman](https://github.com/dotty-staging/collection-strawman)
- [x] [scalap](https://github.com/dotty-staging/scala/tree/dotty-scalap). TODO: upstream changes

## Documentation and Examples Projects
- [x] https://dotty.epfl.ch
- [x] https://github.com/lampepfl/dotty-example-project
- [x] https://github.com/lampepfl/dotty.g8
- [x] https://github.com/lampepfl/dotty-cross.g8

**Blocked**: need a  release of Dotty
