### ISSUE TITLE
Release Dotty 0.9.0-RC1 and 0.8.0

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4649]
- [x] On branch`0.8.x`, set `baseVersion` to `0.8.0`
- [x] Tag `0.8.0`. This will publish artefacts to Sonatype and GitHub Release
- [x] Merge branch `0.8.x` into `master`
- [x] Create branch `0.9.x`
- [x] On `0.9.x`, set `baseVersion` to `0.9.0-RC1`
- [x] Tag `0.9.0-RC1`. This will publish artefacts to Sonatype and GitHub Release
- [x] Add release notes to the GitHub Release
- [x] On `master`, set `baseVersion` to `0.10.0`
- Update `scalaVersion` (and, if applicable, the sbt-dotty version) in the example projects
  - [x] https://github.com/lampepfl/dotty-example-project
  - [x] https://github.com/lampepfl/dotty.g8
  - [x] https://github.com/lampepfl/dotty-cross.g8
  - [x] https://github.com/lampepfl/homebrew-brew
  - [x] https://github.com/lampepfl/packtest
  - [ ] https://github.com/scalacenter/scastie/ 🚫 Scastie uses sbt 0.13
- [x] Make an announcement thread on https://contributors.scala-lang.org
- [x] Publish Blog Post on dotty.epfl.ch
- [x] Tweet the announcement blog post on https://twitter.com/scala_lang

**Comment by allanrenucci** [comment]
Waiting for #4648
