### ISSUE TITLE
Release Dotty 0.10.0-RC1 and 0.9.0 and sbt-dotty 0.2.5

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#5111]
### ~~Release `sbt-dotty` (if there's been any change since 0.2.5)~~
- [ ] Pick a successful build number `nb` from the CI that you want to release. Then run:
  ```
  drone deploy lampepfl/dotty <nb> sbt_release
  ```
- [ ] On `master`, set `sbt-dotty` base version to `0.2.6`

### Release `dotty`
- [x] Look at the [0.10 Milestone](https://github.com/lampepfl/dotty/milestone/7) and reschedule what's still open to the [next milestone](https://github.com/lampepfl/dotty/milestone/8)
- [x] On branch`0.9.x`, set `baseVersion` to `0.9.0`
- [x] Tag `0.9.0`. This will publish artefacts to Sonatype and GitHub Release
- [x] Merge branch `0.9.x` into `master`
- [x] Create branch `0.10.x` from `master`
- [x] On `0.10.x`, set `baseVersion` to `0.10.0-RC1`
- [x] Tag `0.10.0-RC1`. This will publish artefacts to Sonatype and GitHub Release
- [x] Add release notes to the GitHub Release
- [x] On `master`, set `baseVersion` to `0.11.0`
- Update `scalaVersion` (and, if applicable, the `sbt-dotty` version) in the example projects
  - [x] https://github.com/lampepfl/dotty-example-project
  - [x] https://github.com/lampepfl/dotty.g8
  - [x] https://github.com/lampepfl/dotty-cross.g8
  - [x] https://github.com/lampepfl/homebrew-brew
  - [x] https://github.com/lampepfl/packtest
  - [ ] https://github.com/scalacenter/scastie/ 🚫 Scastie uses sbt 0.13
- [x] Make an announcement thread on https://contributors.scala-lang.org
- [x] Publish Blog Post on dotty.epfl.ch
- [x] Tweet the announcement blog post on https://twitter.com/scala_lang

**Comment by allanrenucci** [comment]
I think it would be nice to have #5078 in. Maybe you can have a look @smarter

**Comment by Blaisorblade** [comment]
Let’s also get #5109 in I guess?

**Comment by nicolasstucki** [comment]
Yes. Just merged #5109.
