### ISSUE TITLE
Macro/Inline TODOs

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#5132]
- [x] Let macro authors inspect tree of the original arguments. One should not need to make these arguments by name
- [x] Replace inline match with meta functionalities. Rewrite Tuple.scala (#5182)
- [x] Drop inline optimisations
- [x] Move inline after `Pickling` and before `ReifyQuotes` (#5216)
- [x] Move inline in `ReifyQuotes` and remove `Inlined` from TASTy (#5241)
- [x] Simplify inline accessors (should fix #5097)
- [ ] <del>Substitute by-name parameters directly without creating def bindings for them.</del> (now is imposible as macros are expanded before bindings are inlined)
- [x] <del>Move `dropUnused` simplification after macro expansion.</del> Move macro expnasion before `dropUnused` simplification

**Comment by nicolasstucki** [comment]
Inline should be after `Typer`/`PostTyper`. It should be before pickling or inspecting definitions that contain inline calls will not show the body with inlined calls. Hence we would have two diferent representation of the same tree depending of how it is accessed.

**Comment by nicolasstucki** [comment]
The alternative would be to retain trees at inlining time.

**Comment by nicolasstucki** [comment]
Actually the second might be a better solution
