### ISSUE TITLE
TASTy Reflect - TODOs meta issue

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#5489]
- Documentation
  - Tutorial
    - [x] Basic (#5493) (@nicolasstucki) (1st of December)
    - [ ] In depth (@nicolasstucki, @liufengyun, @biboudis and anyone else with experience)
  - Code docs
    - [ ] [library/src/scala/tasty](https://github.com/lampepfl/dotty/tree/master/library/src/scala/tasty)

- Macro Interface (TASTy reflect)
  - Complete extractor API
    - [ ] Refine extracted types (see #4688 and [paper](https://dl.acm.org/citation.cfm?id=3241658)) (not striclty required, improves usability)
    - [ ] Add useful methods to the API (by need, imposed by prototypes) (validation once all prototypes work)
    - [x] Publish docs (see #5499)
  - Extractor coverage validation
    - [x] Decompiler (student project) (@tuvior and @nicolasstucki ) (end of January 2019)
    - [x] SemanticDB (student project) (@poechsel) (end of January 2019)
    - [ ] Interpreter (@biboudis and [available as master project](https://lamp.epfl.ch/teaching/projects))
  - Implement constructors
    - [x] Add constructors (copiers and tree map) (@nicolasstucki) (#5438) (early January 2019)
- Macro Prototypes
  - Developer ergonomics
    - [lihaoyi/sourcecode](https://github.com/lihaoyi/sourcecode) (@alexarchambault)
      - [x] Implement prototypes
      - [ ] Should some of these be provided by the language/compiler directly?
    - Scalactic macros
      - [x] See #5491 (end of 2018) (@liufengyun)
  - Interpolators
    - Macro interpolator framework 
      - [x] (@nicolasstucki) (mid December 2018)
    - `f` interpolator ([pending/run](https://github.com/lampepfl/dotty/blob/master/tests/pending/run/stringinterpolation_macro-run.scala), [untried/neg](https://github.com/lampepfl/dotty/blob/master/tests/untried/neg/stringinterpolation_macro-neg.scala))
      - [x] basic prototype (#5532) (@nicolasstucki) (mid December 2018)
      - [x] full implmentation ([available as student project](https://lamp.epfl.ch/teaching/projects)) (first semester 2019)
    - `xml` interpolator
      - [x] basic prototype ([allanrenucci/jsx-interpolator](https://github.com/allanrenucci/jsx-interpolator/blob/master/src/main/scala/jsx/internal/QuoteImpl.scala) ) 
      - [x] full implmentation ([available as student project](https://lamp.epfl.ch/teaching/projects)) (first semester 2019)
  - Serialization/Deserialization
    - [ ] Which ones? (@olafurpg) (end of November 2018)
  - Database Queries
    - [ ] Which ones? (@olafurpg) (end of November 2018)

For discussions please write on more specific issues (create one if necessary).

**Comment by nicolasstucki** [comment]
For discussions please write on more specific issues (create one if necessary).
