### ISSUE TITLE
ScalaTest macros

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#5491]
This is thread for issues about implementation of ScalaTest macros (related meta issue #5489)

## TODOS

- [x]  Line number ([source](https://github.com/scalatest/scalatest/blob/3.1.x/common-test/src/main/scala/org/scalatest/LineNumberHelper.scala))
- [x] Position macros ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalactic/src/main/scala/org/scalactic/source/Position.scala))
- [x] Assert & Assume macros ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/Assertions.scala))
    - [x] ==
    - [x] !=
    - [x] === blocked by #5567 #5786
    - [x] >=, <=, >, <: blocked by #5567, but we use Term.Select.copy as walkaround
- [x] assertTypeError ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/Assertions.scala#L659)) blocked by missing `c.parse` + `c.typecheck`
- [x] assertDoesNotCompile ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/Assertions.scala#L690)) blocked by missing `c.parse` + `c.typecheck`
- [x] assertCompiles ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/Assertions.scala#L711)) blocked by missing `c.parse` + `c.typecheck`
- [x] GenFactories macros ([source](https://github.com/scalatest/scalatest/blob/3.1.x/project/GenFactories.scala))
- [x] Requirements macros ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalactic/src/main/scala/org/scalactic/Requirements.scala))
    - [x] require(boolean)
    - [x] requireNonNull(args: Any*)
    - [x] requireState
- [x] Snapshot macros ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalactic/src/main/scala/org/scalactic/Snapshots.scala))
- [x] DiagrammedAssertion macros ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/DiagrammedAssertions.scala))
    - [x] macro implementation
    - [x] usage blocked by overriding macros
- [x] Expectation macros ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/Expectations.scala))
    - [x] expect
    - [x] expect compile: blocked by missing `c.parse` + `c.typecheck`
- [x] Matcher macros ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/matchers/Matcher.scala))
- [x] Matchers macros ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/Matchers.scala))
    - [x] shoud
    - [x] should compile: blocked by missing `c.parse` + `c.typecheck`
- [x] MatcherPatternMacro ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/matchers/MatchPatternMacro.scala))
- [x] MatchPatternWord ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/words/MatchPatternWord.scala))
- [x] BeWord ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/words/BeWord.scala))
- [x] NoWord ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/words/NotWord.scala))
- [x] ResultOfNotWordForAny ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/words/ResultOfNotWordForAny.scala))
- [x] LongAnyVal ([source](https://github.com/scalatest/scalatest/blob/3.1.x/project/templates/LongAnyVal.template#L1041))
- [x] CharAnyVal ([source](https://github.com/scalatest/scalatest/blob/3.1.x/project/templates/CharAnyVal.template#L661))
- [x] FloatAnyVal ([source](https://github.com/scalatest/scalatest/blob/3.1.x/project/templates/FloatAnyVal.template#L697))
- [x] DoubleAnyVal ([source](https://github.com/scalatest/scalatest/blob/3.1.x/project/templates/DoubleAnyVal.template#L693))
- [x] IntAnyVal ([source](https://github.com/scalatest/scalatest/blob/3.1.x/project/templates/IntAnyVal.template#L1000))
- [x] NumericString ([source](https://github.com/scalatest/scalatest/blob/57151f83937a4adb23d402efecfe76d4c96c73ac/scalactic-macro/src/main/scala/org/scalactic/anyvals/NumericString.scala#L2757))
- [x] PercentageInt ([source](https://github.com/scalatest/scalatest/blob/57151f83937a4adb23d402efecfe76d4c96c73ac/scalactic-macro/src/main/scala/org/scalactic/anyvals/PercentageInt.scala#L34)
- [x] RegexString ([source](https://github.com/scalatest/scalatest/blob/57151f83937a4adb23d402efecfe76d4c96c73ac/scalactic-macro/src/main/scala/org/scalactic/anyvals/RegexString.scala#L192))

## Issues

- [x] Overriding of macros ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/junit/AssertionsForJUnit.scala#L105-L111), [source](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/DiagrammedAssertions.scala))
- [x] Implementation of macro are private ([source](https://github.com/scalatest/scalatest/blob/3.1.x/scalactic/src/main/scala/org/scalactic/Requirements.scala#L220-L249), issue #5492 )
- [x] liftSeq in lib (#5543)
```Scala
  private def liftSeq(args: Seq[Expr[Any]]): Expr[Seq[Any]] = args match {
    case x :: xs  => '{ (~x) +: ~(liftSeq(xs))  }
    case Nil => '(Seq(): Seq[Any])
  }
```
- [x] `import Term._` and `import refl._` are tedious
- [x] bug #5533 
- [x] bug #5536
- [x] bug #5547
- [x] constructors required to support generic `>` operation that work on unknown types. Blocked by #5438  #5567 
- [x] a helper method like `def typeOf[T]: Type` will be helpful
- [x] seal to a method type: useful in `===` case #5563 
- [x] bug with line number #5629 
- [ ] Runtime reflection support #5639
- [ ] `IsSelectModule` not friendly #7204
- [x] `copy` not useful
- [x] missing `selectApply` on any term
- [x] bug #5715
- [x] report warnings with precise positions
- [x] bug #5786
- [x] bug #5612 
- [x] bug #5831
- [x] bug #6109
- [x] bug #5962
- [x] bug #6048 
- [x] bug #5951 
- [x] bug #5924
- [ ] bug #6114
- [x] bug #6119

**Comment by LPTK** [comment]
> If there is always mutual dependencies between macros project and its main project, quotes & splices will be useless for writing macros.

Can't you define the macros in the same project as the classes they quote? In both scala.reflect and Squid, that's how it works. It's just that you won't be able to _call_ these macros from the same project.

For example, in scala.reflect you can write:

```scala
class A { val x = 42 }
def A: Int = macro `A macro`
def `A macro`(c: whitebox.Context): c.Expr[Int] = {
  c.universe.reify{new A().x}  // similar to a typed quote
}
```

**Comment by liufengyun** [comment]
@LPTK If the macros are *not* used in the main project, then it makes sense to merge the two projects. This is the walkaround I took https://github.com/dotty-staging/scalatest/commit/642050c4c47ebdc2a0727668dae46cdc6a9e5daf for ScalaTest. 

However, I assume there are a lot of projects where the macros are used in the main project and refers to symbols defined in the main project, then things becomes subtle.

**Comment by liufengyun** [comment]
Just a Log: ScalaTest changes the semantics of `Boolean.|` to be short-cutting. This cannot be implemented (**maybe not a bad thing**) in Dotty, due to the `lifting` of parameters during inlining.

```Scala
  class Stateful {
    var state = false
    def changeState: Boolean = {
      state = true

      state
    }
  }

  describe("The assume method") {
    it("should short-circuit | when first condition was true") {
      val s = new Stateful
      assume(true | s.changeState)
      assert(s.state == false)
    }
  }
```

**Comment by liufengyun** [comment]
@nicolasstucki Just discussed with @cheeseng and @bvenners, I learned that macros like  `assertDoesNotCompile` are super useful for library authors.

Github search for [assertDoesNotCompile](https://github.com/search?l=Scala&q=assertDoesNotCompile&type=Code) shows 299 results.

**Comment by nicolasstucki** [comment]
@liufengyun  can we close this issue? All the macro related issues have been fixed. All remaining tasks have their own issue.

**Comment by liufengyun** [comment]
We may close now. We need to make an upstream PR after the meta-programming API refactoring.
