### ISSUE TITLE
Release Dotty 0.12.0-RC1 and 0.11.0

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#5718]
## Checklist in English

- [x] On branch`0.11.x`, set `baseVersion` to `0.11.0`
- [x] Tag `0.11.0`. This will publish artefacts to Sonatype and GitHub Release
- [x] Merge branch `0.11.x` into `master`
- [x] Look at the [0.12 Milestone](https://github.com/lampepfl/dotty/milestone/9) and reschedule what's still open to the [next milestone](https://github.com/lampepfl/dotty/milestone/10)
- [x] Create branch `0.12.x` from `master`
- [x] On `0.12.x`, set `baseVersion` to `0.12.0-RC1`
- [x] Tag `0.12.0-RC1`. This will publish artefacts to Sonatype and GitHub Release
- [x] On `master`, set `baseVersion` to `0.13.0`
- [x] Add release notes to the GitHub Release
- Update `scalaVersion` (and, if applicable, the `sbt-dotty` version) in the example projects
  - [x] https://github.com/lampepfl/dotty-example-project
  - [x] https://github.com/lampepfl/dotty-example-project/tree/mill
  - [x] https://github.com/lampepfl/dotty.g8
  - [x] https://github.com/lampepfl/dotty-cross.g8
  - [x] https://github.com/lampepfl/homebrew-brew
  - [x] https://github.com/lampepfl/packtest
  - [ ] https://github.com/scalacenter/scastie/ 🚫 Scastie uses sbt 0.13
- [x] Publish Blog Post on dotty.epfl.ch (#5737)
- [x] Make an announcement thread on https://contributors.scala-lang.org
- [x] Tweet the announcement blog post on https://twitter.com/scala_lang

## Checklist in GIT

```shell
git checkout 0.11.x

# change val baseVersion = "0.11.0-RC1" to val baseVersion = "0.11.0"

git commit -am 'Release Dotty 0.11.0'

git tag 0.11.0

git push --follow-tags --set-upstream origin 0.11

git checkout master

git merge 0.11.x

git push

# milestones

git checkout -b 0.12.x

# change val baseVersion = "0.11.0" to val baseVersion = "0.12.0-RC1"

git commit -am 'Release Dotty 0.12.0-RC1'

git tag 0.12.0-RC1

git push --follow-tags --set-upstream origin 0.12.x

# draft the release, get contents from:

gren changelog -G --override -D prs --tags=0.11.0-RC1..0.12.0-RC1

git checkout master

#change val baseVersion = "0.12.0-RC1" to val baseVersion = "0.13.0"

git commit -am 'Set baseVersion to 0.13.0'
```

**Comment by biboudis** [comment]
For future reference:

```shell
git checkout 0.11.x

# change val baseVersion = "0.11.0-RC1" to val baseVersion = "0.11.0"

git commit -am 'Release Dotty 0.11.0'

git tag 0.11.0

git push --follow-tags --set-upstream origin 0.11

git checkout master

git merge 0.11.x

git push

# milestones

git checkout -b 0.12.x

# change val baseVersion = "0.11.0" to val baseVersion = "0.12.0-RC1"

git commit -am 'Release Dotty 0.12.0-RC1'

git tag 0.12.0-RC1

git push --follow-tags --set-upstream origin 0.12.x

# draft the release, get contents from:

gren changelog -G --override -D prs --tags=0.11.0..0.11.0-RC1

git checkout master

#change val baseVersion = "0.12.0-RC1" to val baseVersion = "0.13.0"

git commit -am 'Set baseVersion to 0.13.0'
```
