### ISSUE TITLE
Release Dotty 0.14.0-RC1 and 0.13.0

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#6235]
## Checklist in English

- [x] On branch`0.13.x`, set `baseVersion` to `0.13.0`
- [x] Tag `0.13.0`. This will publish artefacts to Sonatype and GitHub Release
- [x] Merge branch `0.13.x` into `master`
- [x] Look at the [0.14 Milestone](https://github.com/lampepfl/dotty/milestone/11) and reschedule what's still open to the [next milestone](https://github.com/lampepfl/dotty/milestone/12)
- [x] Create branch `0.14.x` from `master`
- [x] On `0.14.x`, set `baseVersion` to `0.14.0-RC1`
- [x] Tag `0.14.0-RC1`. This will publish artefacts to Sonatype and GitHub Release
- [x] On `master`, set `baseVersion` to `0.15.0`
- [x] Add release notes to the GitHub Release
- Update `scalaVersion` (and, if applicable, the `sbt-dotty` version) in the example projects
  - [x] https://github.com/lampepfl/dotty-example-project 
  - [ ] https://github.com/lampepfl/dotty-example-project/tree/mill 🚫(check https://github.com/lampepfl/dotty-example-project/pull/26)
  - [x] https://github.com/lampepfl/dotty.g8
  - [x] https://github.com/lampepfl/dotty-cross.g8
  - [x] https://github.com/lampepfl/homebrew-brew
  - [x] https://github.com/lampepfl/packtest
  - [ ] https://github.com/scalacenter/scastie/ 🚫 Scastie uses sbt 0.13
- [x] Update CHANGELOG.md
- [x] Publish Blog Post on dotty.epfl.ch
- [x] Make an announcement thread on https://contributors.scala-lang.org
- [x] Tweet the announcement blog post on https://twitter.com/scala_lang

## Checklist in GIT

```shell
# The following commands assume a remote tracking repository named
# `upstream` pointing to the main Dotty repo:
#
# $ git remote get-url upstream
# https://github.com/lampepfl/dotty.git

git checkout 0.13.x

# Change val baseVersion = "0.13.0-RC1" to val baseVersion = "0.13.0"

git commit -am 'Release Dotty 0.13.0'
git tag 0.13.0
git push upstream 0.13.0

git checkout master
git merge 0.13.x

# Make sure the merge doesn't break anything. In doubt, create a PR to run the CL
git push upstream master

# Milestones

git checkout -b 0.14.x

# Change val baseVersion = "0.14.0" to val baseVersion = "0.14.0-RC1"

git commit -am 'Release Dotty 0.14.0-RC1'
git tag 0.14.0-RC1
git push upstream 0.14.x
git push upstream 0.14.0-RC1

# Draft the release, get contents from:
gren changelog -G --override -D prs --tags=0.13.0-RC1..0.14.0-RC1

git checkout master

# Change val baseVersion = "0.14.0" to val baseVersion = "0.15.0"

git commit -am 'Set baseVersion to 0.15.0'
git push upstream master
```

**Comment by allanrenucci** [comment]
I slightly edited the git checklist

**Comment by anatoliykmetyuk** [comment]
@biboudis can you please have a look at the drafts at the release page and see if these are fine?

Also, some questions:

SBT plugin version 0.3.2 doesn't seem to be published by the CI. This is because `dotty-bootstrapped/publishSigned` is used for publishing, and it doesn't seem to include the SBT plugin:

```s
def asDottyRoot(implicit mode: Mode): Project = project.withCommonSettings.
      aggregate(`dotty-interfaces`, dottyLibrary, dottyCompiler, dottyDoc, `dotty-sbt-bridge`).
      bootstrappedAggregate(`scala-library`, `scala-compiler`, `scala-reflect`, scalap, `dotty-language-server`).
```

What's the procedure for publishing the SBT plugin?

Also, we do not update the following projects, right?

- https://github.com/lampepfl/dotty-example-project/tree/mill 🚫(check lampepfl- dotty-example-project#26)
- https://github.com/scalacenter/scastie/ 🚫 Scastie uses sbt 0.13

Another thing: the CI did not seem to include the sources in the Assets of the releases on the GitHub releases page. For all the other releases, these are present. Do we include these manually?

**Comment by biboudis** [comment]
I just checked the previous releases. The src's do not appear there as well (when you edit the page). I think they get attached automatically.

@smarter publishes the plugin separately and independently of this lifecycle I think.

LGTM @anatoliykmetyuk

**Comment by smarter** [comment]
> What's the procedure for publishing the SBT plugin?


```shell
drone deploy lampepfl/dotty $id sbt_release
```
where $id is a job id from the CI, e.g. 12070 for http://dotty-ci.epfl.ch/lampepfl/dotty/12070.

But there's been no changes to sbt-dotty since the last release so there's nothing that needs to be published right now.

**Comment by anatoliykmetyuk** [comment]
Unfortunately, I can't publish the post to Scala Contributors since "the new users can only include 10 links in their post". @biboudis can you please do it for me? The source is [here](https://pastebin.com/FcCWf9F0).

**Comment by biboudis** [comment]
Done

**Comment by biboudis** [comment]
homebrew-brew and packtest are merged right @anatoliykmetyuk ?

**Comment by anatoliykmetyuk** [comment]
Yes, they are merged

**Comment by biboudis** [comment]
I updated the checklist above 👍
