### ISSUE TITLE
Release Dotty 0.15.0-RC1 and 0.14.0

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#6553]
- [x] Publish artifacts to Maven via CI
  - [x] On branch`0.14.x`, set `baseVersion` to `0.14.0` and `git tag` it `0.14.0`. This will publish artefacts to Sonatype and GitHub Release
  - [x] Merge branch `0.14.x` into `master`, to guarantee that all of the `0.14.x` commits are propagated to `master`
  - [x] Look at the [0.15 Milestone](https://github.com/lampepfl/dotty/milestone/12) and reschedule what's still open to the [next milestone](https://github.com/lampepfl/dotty/milestone/13)
  - [x] Create branch `0.15.x` from `master`
  - [x] On `0.15.x`, set `baseVersion` to `0.15.0-RC1` and `git tag` `0.15.0-RC1`. This will publish artefacts to Sonatype and GitHub Release.
  - [x] On `master`, set `baseVersion` to `0.16.0`
- [x] Update `scalaVersion` (and, if applicable, the `sbt-dotty` version) in the Dotty ecosystem projects
  - [x] https://github.com/lampepfl/dotty-example-project 
  - [x] https://github.com/lampepfl/dotty-example-project/tree/mill
  - [x] https://github.com/lampepfl/dotty.g8
  - [x] https://github.com/lampepfl/dotty-cross.g8
  - [x] https://github.com/lampepfl/homebrew-brew
  - [x] https://github.com/lampepfl/packtest
  - [x] https://github.com/scalacenter/scastie
  - [x] Dotty itself – update the `referenceVersion` in the `master` branch to `<rc-version>`. This is the version of Dotty used to compile the Dotty codebase on `master`.
  - [x] Scalac CI, like this: scala/scala#7993
- [x] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Publish Blog Post on dotty.epfl.ch
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

**Comment by smarter** [comment]
The version of dotty used in the scalac CI should also be updated like this: https://github.com/scala/scala/pull/7993
