### ISSUE TITLE
Outstanding language changes

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#6572]
Here is a list of language changes that we committed to or are at least strongly considering. It would be good to get these sorted out quickly before we keep the feature envelope ready.

 - [x] Revert `@volatile` lazy vals. It changes runtime behavior, which we want to avoid. #6579 @smarter 
 - [x] Drop nonlocal returns: #6623. @OlivierBlanvillain
 - [x] Allow enums to extend java.lang.Enum #6576 @anatoliykmetyuk 
 - [ ] ~Generalization of structural types~ -- deferred
 - [x] Implement `@alpha` #6597  @odersky 
 - [x] Import implied #6594 @odersky
