### ISSUE TITLE
Release Dotty 0.16.0-RC3 and 0.15.0 - (Scala Days Release)

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#6632]
- [x] Publish artifacts to Maven via CI
  - [x] On branch`0.15.x`, set `baseVersion` to `0.15.0` and `git tag` it as `0.15.0`. This will publish artefacts to Sonatype and GitHub Release
  - [x] Merge branch `0.15.x` into `master` to guarantee that all of the `0.15.x` commits are propagated to `master`
  - [x] Look at the [milestone](https://github.com/lampepfl/dotty/milestone/13) of the RC version being released. Move all the open issues from it to the [next milestone](https://github.com/lampepfl/dotty/milestone/14).
  - [x] Create branch `0.16.x` from `master`
  - [x] On `0.16.x`, set `baseVersion` to `0.16.0-RC3` and `git tag` it as `0.16.0-RC3`. This will publish artefacts to Sonatype and GitHub Release.
  - [x] On `master`, set `baseVersion` to `0.17.0`
- [ ] Update `scalaVersion` (and, if applicable, the `sbt-dotty` version) in the Dotty ecosystem projects
  - [x] https://github.com/lampepfl/dotty-example-project
  - [x] https://github.com/lampepfl/dotty-example-project/tree/mill
  - [x] https://github.com/lampepfl/dotty.g8 [![Build Status](https://travis-ci.org/lampepfl/dotty.g8.svg?branch=master)](https://travis-ci.org/lampepfl/dotty.g8/)
    - [x] Committed to `master`
  - [x] https://github.com/lampepfl/dotty-cross.g8 [![Build Status](https://travis-ci.org/lampepfl/dotty-cross.g8.svg?branch=master)](https://travis-ci.org/lampepfl/dotty-cross.g8/)
    - [x] Committed to `master`
  - [x] https://github.com/lampepfl/homebrew-brew [![Build Status](https://travis-ci.org/lampepfl/homebrew-brew.svg?branch=master)](https://travis-ci.org/lampepfl/homebrew-brew)
    - [x] Committed to `master`
    - SHA256 sum for the artifact: `wget -q -O- https://github.com/lampepfl/dotty/releases/download/0.16.0-RC3/sha256sum.txt | grep ".tar.gz"`
  - [x] https://github.com/lampepfl/packtest [![Build Status](https://travis-ci.org/lampepfl/packtest.svg?branch=master)](https://travis-ci.org/lampepfl/packtest)
    - [x] Committed to `master`
  - [x] https://github.com/scalacenter/scastie
    - [x] PR submitted
    - [x] PR merged
    - [x] https://scastie.scala-lang.org/ -> Build Settings -> Dotty mentions `0.16.0-RC3`
  - [x] Dotty reference compiler [![Build Status](http://dotty-ci.epfl.ch/api/badges/lampepfl/dotty/status.svg)](http://dotty-ci.epfl.ch/lampepfl/dotty)
    - [x] PR submitted
    - [x] PR merged
  - [ ] Scalac [![Build Status](https://travis-ci.org/scala/scala.svg?branch=2.13.x)](https://travis-ci.org/scala/scala)
    - [x] PR submitted
    - [ ] PR merged
- [ ] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Publish Blog Post on dotty.epfl.ch
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

[Instructions on how to release](https://dotty.epfl.ch/docs/contributing/release.html)

**Comment by biboudis** [comment]
🎉
