### ISSUE TITLE
Meta-programming TODOs

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#6688]
* Quotes
  - [x] Correctly contextualize quotes and splices
    - [x] Homogenize `run` and `$` (#6689)
    - [x] Add `QuoteConext` (#6700)
    - [x] Move `show` to `QuoteContext` (#6700)
    - [x] Move reflection inside `QuoteContext` (#6723)
    - [x] Move quote unpickling to `QuoteConext`
    - [x] Lift primitives using the `QuoteConext` (#6793)
    - [x] Define quote as ```def `'`[T](e: T): given QuoteContext => Expr[T]``` (#6881)
    - [x] Define type quote as ```def `'`[T]: given QuoteContext => Type[T]```
    - [x] Define splice as ```def `$`[T](expr: given QuoteContext => Expr[T]): T``` (#6881)
  - [x] Add `implicit match` functionality (#6819)
* Quote patterns
  - [x] Quote patterns with type splices (#6504)
  - [x] Type quote patterns (#6930)
  - [ ] Port `inline match` tests
* TASTy reflect API
  - [ ] Make the core interface Java only (to avoid conflicts from different classloaders).
  - [ ] #5489
