### ISSUE TITLE
Release Dotty 0.18.1-RC1 and 0.17.0

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#7118]
- [x] #7114  merged
- [x] Finalize the the stable and RC releases
  - [x] Look at the milestone of the RC version being released. Move all the open issues from it to the next milestone.
  - [x] Merge branch `0.17.x` into `master` to guarantee that all of the `0.17.x` commits are propagated to `master`
- [x] Publish artifacts to Maven via CI
  - [x] On branch `0.17.x`, set `baseVersion` to `0.17.0` and `git tag` it as `0.17.0`. This will publish artefacts to Sonatype and GitHub Release
  - [x] Create branch `0.18.x` from `master`
  - [x] On `0.18.x`, set `baseVersion` to `0.18.1-RC1` and `git tag` it as `0.18.1-RC1`. This will publish artefacts to Sonatype and GitHub Release.
  - [x] On `master`, set `baseVersion` to `0.19.1`
- [ ] Update `scalaVersion` (and, if applicable, the `sbt-dotty` version) in the Dotty ecosystem projects
  - [x] https://github.com/lampepfl/dotty-example-project [![Build Status](https://travis-ci.org/lampepfl/dotty-example-project.svg?branch=master)](https://travis-ci.org/lampepfl/dotty-example-project)
    - [x] Committed to `master`
  - [x] https://github.com/lampepfl/dotty-example-project/tree/mill
  - [x] https://github.com/lampepfl/dotty-staging.g8 [![Build Status](https://travis-ci.org/lampepfl/dotty-staging.g8.svg?branch=master)](https://travis-ci.org/lampepfl/dotty-staging.g8)
    - [x] PR submitted
    - [x] PR merged
  - [x] https://github.com/lampepfl/dotty.g8 [![Build Status](https://travis-ci.org/lampepfl/dotty.g8.svg?branch=master)](https://travis-ci.org/lampepfl/dotty.g8/)
    - [x] Committed to `master`
  - [x] https://github.com/lampepfl/dotty-cross.g8 [![Build Status](https://travis-ci.org/lampepfl/dotty-cross.g8.svg?branch=master)](https://travis-ci.org/lampepfl/dotty-cross.g8/)
    - [x] Committed to `master`
  - [x] https://github.com/lampepfl/homebrew-brew [![Build Status](https://travis-ci.org/lampepfl/homebrew-brew.svg?branch=master)](https://travis-ci.org/lampepfl/homebrew-brew)
    - [x] Committed to `master`
    - SHA256 sum for the artifact: `wget -q -O- https://github.com/lampepfl/dotty/releases/download/0.18.1-RC1/sha256sum.txt | grep ".tar.gz"`
  - [x] https://github.com/lampepfl/packtest [![Build Status](https://travis-ci.org/lampepfl/packtest.svg?branch=master)](https://travis-ci.org/lampepfl/packtest)
    - [x] Committed to `master`
  - [ ] https://github.com/lampepfl/xml-interpolator [![Build Status](https://travis-ci.org/lampepfl/xml-interpolator.svg?branch=master)](https://travis-ci.org/lampepfl/xml-interpolator)
    - [x] PR submitted
    - [ ] PR merged
  - [x] https://github.com/scalacenter/scastie
    - [x] PR submitted
    - [x] PR merged
    - [x] https://scastie.scala-lang.org/ -> Build Settings -> Dotty mentions `0.18.1-RC1`
  - [x] Dotty reference compiler [![Build Status](http://dotty-ci.epfl.ch/api/badges/lampepfl/dotty/status.svg)](http://dotty-ci.epfl.ch/lampepfl/dotty)
    - [x] PR submitted
    - [x] PR merged
  - [ ] Scalac [![Build Status](https://travis-ci.org/scala/scala.svg?branch=2.13.x)](https://travis-ci.org/scala/scala)
    - [x] PR submitted (https://github.com/scala/scala/pull/8387)
    - [ ] PR merged
- [x] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Publish Blog Post on dotty.epfl.ch
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

[Instructions on how to release](https://dotty.epfl.ch/docs/contributing/release.html)

**Comment by bishabosha** [comment]
do we need to release 18.1 to include the 2.13 lib?

**Comment by anatoliykmetyuk** [comment]
> do we need to release 18.1 to include the 2.13 lib?

/cc @smarter

**Comment by biboudis** [comment]
I am not closing this yet because I am finishing up this https://github.com/scala/scala/pull/8387

**Comment by smarter** [comment]
>  On master, set baseVersion to 0.19.1

Wait, why 0.19.1 instead of 0.19.0 ? The only reason for using 0.18.1 was to be able to distinguish nightly built against the 2.12 stdlib and those built against the 2.13 stdlib, but now that we've switched, we can go back to .0 as normal.

**Comment by bishabosha** [comment]
It’s enshrined in the blog as the new standard now

**Comment by smarter** [comment]
Blog posts are mutable:)
