### ISSUE TITLE
Release Dotty 0.19.0-RC1 and 0.18.1

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#7265]
- [x] Merge #7263
- [x] Finalize the the stable and RC releases
  - [x] Look at the milestone of the RC version being released. Move all the open issues from it to the next milestone.
  - [x] Merge branch `0.18.x` into `master` to guarantee that all of the `0.18.x` commits are propagated to `master`
- [x] Publish artifacts to Maven via CI. Use the following command: `bash <(curl -sL https://raw.githubusercontent.com/lampepfl/dotty/master/docs/docs/contributing/release.sh) 18`
  - [x] On branch `0.18.x`, set `baseVersion` to `0.18.1` and `git tag` it as `0.18.1`. This will publish artefacts to Sonatype and GitHub Release
  - [x] Create branch `0.19.x` from `master`
  - [x] On `0.19.x`, set `baseVersion` to `0.19.0-RC1` and `git tag` it as `0.19.0-RC1`. This will publish artefacts to Sonatype and GitHub Release.
  - [x] On `master`, set `baseVersion` to `0.20.0`
- [ ] Update `scalaVersion` (and, if applicable, the `sbt-dotty` version) in the Dotty ecosystem projects
  - [x] https://github.com/lampepfl/dotty-example-project [![Build Status](https://travis-ci.org/lampepfl/dotty-example-project.svg?branch=master)](https://travis-ci.org/lampepfl/dotty-example-project) – build fails because it incorrectly considers 0.19.1-... version as latest nightly
    - [x] Committed to `master`
  - [x] https://github.com/lampepfl/dotty-example-project/tree/mill
  - [x] https://github.com/lampepfl/dotty.g8 [![Build Status](https://travis-ci.org/lampepfl/dotty.g8.svg?branch=master)](https://travis-ci.org/lampepfl/dotty.g8/)
    - [x] Committed to `master`
  - [x] https://github.com/lampepfl/dotty-cross.g8 [![Build Status](https://travis-ci.org/lampepfl/dotty-cross.g8.svg?branch=master)](https://travis-ci.org/lampepfl/dotty-cross.g8/)
    - [x] Committed to `master`
  - [x] https://github.com/lampepfl/dotty-staging.g8 [![Build Status](https://travis-ci.org/lampepfl/dotty-staging.g8.svg?branch=master)](https://travis-ci.org/lampepfl/dotty-staging.g8)
    - [x] Committed to `master`
  - [x] https://github.com/lampepfl/homebrew-brew [![Build Status](https://travis-ci.org/lampepfl/homebrew-brew.svg?branch=master)](https://travis-ci.org/lampepfl/homebrew-brew)
    - [x] Committed to `master`
    - SHA256 sum for the artifact: `wget -q -O- https://github.com/lampepfl/dotty/releases/download/0.19.0-RC1/sha256sum.txt | grep ".tar.gz"`
  - [x] https://github.com/lampepfl/packtest [![Build Status](https://travis-ci.org/lampepfl/packtest.svg?branch=master)](https://travis-ci.org/lampepfl/packtest)
    - [x] Committed to `master`
  - [ ] https://github.com/lampepfl/xml-interpolator [![Build Status](https://travis-ci.org/lampepfl/xml-interpolator.svg?branch=master)](https://travis-ci.org/lampepfl/xml-interpolator)
    - [x] PR submitted
    - [ ] PR merged
  - [x] https://github.com/scalacenter/scastie
    - [x] PR submitted
    - [x] PR merged
    - [x] https://scastie.scala-lang.org/ -> Build Settings -> Dotty mentions `0.19.0-RC1`
  - [x] Dotty reference compiler [![Build Status](http://dotty-ci.epfl.ch/api/badges/lampepfl/dotty/status.svg)](http://dotty-ci.epfl.ch/lampepfl/dotty)
    - [x] PR submitted
    - [x] PR merged
  - [ ] Scalac [![Build Status](https://travis-ci.org/scala/scala.svg?branch=2.13.x)](https://travis-ci.org/scala/scala)
    - [x] PR submitted
    - [ ] PR merged
- [x] Announce the release
  - [x] Publish releases for the RC and stable versions on GitHub Releases
  - [x] Merge #7251
  - [x] Publish Blog Post on dotty.epfl.ch
  - [x] Make an announcement thread on https://contributors.scala-lang.org
  - [x] Tweet the announcement blog post on https://twitter.com/scala_lang

[Instructions on how to release](https://dotty.epfl.ch/docs/contributing/release.html)

**Comment by smarter** [comment]
>  On 0.19.x, set baseVersion to 0.19.0-RC1 and git tag it as 0.19.0-RC1. This will publish artefacts to Sonatype and GitHub Release.

Status: this is currently blocked due to  a problem with sbt-pgp: https://github.com/lampepfl/dotty/pull/7279

**Comment by anatoliykmetyuk** [comment]
Status update.

After merging #7279 into both master and 0.19.x, the build has apparently stalled: https://dotty-ci.epfl.ch/lampepfl/dotty/1494/1/8. The `publish_release` task was taking 1.5 hours (versus around 20 minutes for 0.18.1-RC1 version https://dotty-ci.epfl.ch/lampepfl/dotty/1066/1/8) with the last line being:

```
sbt server started at local:///root/.sbt/1.0/server/a31a1d86c7bb9f498497/sock
```

This line appeared after `sbtPublish` command, which was supposed to be doing:

```
"$SBT" -DSBT_PGP_USE_GPG=false "$RELEASE_CMD"
```

(see https://github.com/lampepfl/dotty/pull/7279/files#diff-d105bf9112167bd189ba65fb2285cc04R32).

If you look up `sbtPublish` in the [previous failed attempt](https://dotty-ci.epfl.ch/lampepfl/dotty/1487/1/8) to publish 0.19.0-RC1, you'll see:

```
+ ./project/scripts/sbtPublish ";project dotty-bootstrapped ;publishSigned ;sonatypeBundleRelease" | 169s
...
162 | [info] Set current project to dotty (in build file:/drone/src/) | 179s
163 | [info] Set current project to dotty-bootstrapped (in build file:/drone/src/) | 179s
```

The stalled case in question behaves the same way as the failed (and non-stalled) case, except that these two lines are replaced with the `sbt server started ...` message.

It looks like the release commands from the `$RELEASE_CMD` variable stopped being propagated to SBT and SBT just started a server and waited there passively after #7279.

The only change to the way SBT is called was adding the envvar flag. In principle that should be OK, and locally this format of calling SBT works. However, to be rather safe than sorry, I have committed the following to 0.19.x: https://github.com/lampepfl/dotty/commit/3b20752510361e331db196d81209321238d8bfdc

We'll see how it goes: https://dotty-ci.epfl.ch/lampepfl/dotty/1498

**Comment by anatoliykmetyuk** [comment]
Update.

Looks likes the signing still doesn't work on 0.19.x:

https://dotty-ci.epfl.ch/lampepfl/dotty/1498

[error] gpg: no default secret key: No secret key
[error] gpg: signing failed: No secret key

However it didn't stall at least!

Nightly (master branch without the anti stall commit I mentioned) is stalled though: 

https://dotty-ci.epfl.ch/lampepfl/dotty/1499

So probably the flag is indeed causing stalling for some strange reason...

**Comment by anatoliykmetyuk** [comment]
https://github.com/lampepfl/dotty/blob/187bd85b0bbdb37c9eba447e23df90b79192626f/project/scripts/sbtPublish#L32 – SBT command gets two parameters.
https://github.com/lampepfl/dotty/blob/187bd85b0bbdb37c9eba447e23df90b79192626f/project/scripts/sbt#L7 – however, it is designed to accept one and only one parameter, disregarding all the other ones.

So I assume in the stall scenario SBT is called with `-DSBT_PGP_USE_GPG=false` being the last parameter passed.

Also I have erroneously assumed that `-Dparam` sets an envvar – it sets a system property, hence `gpg` is still used, and, since the code for its setup is dropped, it doesn't work (and hence doesn't run out of memory).

I have made the following commit to 0.19.x that will hopefully address these problems: https://github.com/lampepfl/dotty/commit/74791f22123528f1f0fa513dd988c37a7d8e7556

**Comment by biboudis** [comment]
The scalac (if needed) will be on top of https://github.com/scala/scala/pull/8387 since its not merged yet.

**Comment by anatoliykmetyuk** [comment]
0.19.0-RC1 was successfully published to Maven Central

**Comment by anatoliykmetyuk** [comment]
Looks like 0.18.1 was corrupted:

https://dotty-ci.epfl.ch/lampepfl/dotty/1502/1/8

```
[error] java.io.IOException: PUT operation failed because the destination file exists and overwriting is disabled
```

Nothing was published to Maven Central from 0.18.1 though, so it must be the staging area of Sonatype. /cc @smarter

**Comment by smarter** [comment]
The error message tells us that we could force overwriting of the staging area by adding a few settings in the build:
```
[error] Otherwise fix the double publishing, or relax the setting as follows:
[error]     publishConfiguration := publishConfiguration.value.withOverwrite(true)
[error]     publishLocalConfiguration := publishLocalConfiguration.value.withOverwrite(true)
```
Anyway, I've now manually dropped the staging repo, so 0.18.1 should be publishable.

**Comment by anatoliykmetyuk** [comment]
Thanks, I've relaunched it.

**Comment by anatoliykmetyuk** [comment]
I'm ignoring Scalac until scala/scala#8387 is merged

**Comment by anatoliykmetyuk** [comment]
Current status:

- Both 0.19.0-RC1 and 0.18.1 binaries are published and available
- All of the ecosystem projects are updated as planned, except:
  - Dotty example project updated and works fine but fails Travis – lampepfl/dotty-example-project#33
  - Homebrew updated but fails Travis – lampepfl/homebrew-brew#21 – from the logs it follows that dotty was fetched correctly from Homebrew but Dottydoc now behaves differently, hence the failure
  - XML Interpolator is stuck at version 0.17.0-RC1, updating it requires a deal of work: lampepfl/xml-interpolator#22
  - Scalac is not updated, pending scala/scala#8387
- Blog article is ready for merge

Other stuff:

- Nightly builds should work again after #7285 is merged
- The release is now mostly automated via https://github.com/lampepfl/dotty-release-scripts

**Comment by bishabosha** [comment]
is this ok to close?
