### ISSUE TITLE
Enum Improvements Epic

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#7501]
- [x] enums should have sensible flags: https://github.com/lampepfl/dotty/issues/5034
- [x] forbid extending `java.lang.Enum` outside of an `enum` https://github.com/lampepfl/dotty/issues/7499
- [x] allow extending `java.lang.Enum` arbitrarily with `3.0-migration` https://github.com/lampepfl/dotty/issues/7174
- [ ] desugar parent `java.lang.Enum` before TASTy https://github.com/lampepfl/dotty/issues/7478
- [X] `toString` ergonomics https://github.com/lampepfl/dotty/issues/7227
- [X] `.values` on enum companion is not in order: https://github.com/lampepfl/dotty/issues/6663
- [X] drop `scala.runtime.EnumValues`: https://github.com/lampepfl/dotty/issues/6620
- [x] Require that the first class in the extends clause of an enum case is the enum class: https://github.com/lampepfl/dotty/issues/6601 
- [x] variance not copied from base class type parameters: https://github.com/lampepfl/dotty/issues/9260, #9509
- [x] serialization incorrect for simple enum cases: https://github.com/lampepfl/dotty/issues/9179
- [x] bytecode issues
  - [x] `Bad type operand on stack`: https://github.com/lampepfl/dotty/issues/7424, https://github.com/lampepfl/dotty/issues/6664
  - [x] `java.lang.NoSuchFieldError`: https://github.com/lampepfl/dotty/issues/7410, https://github.com/lampepfl/dotty/issues/6677, https://github.com/lampepfl/dotty/issues/7287, https://github.com/lampepfl/dotty/issues/7991
- [x] Decide if we drop `scala.Enum` #9873 
  - Answer for this is we rename it to `scala.reflect.Enum`
- [x] Allowing new mixins in individual cases for java enums: #9162 (decided not really a problem)
- [x] Decide if `.apply` on enum companion should give precise type or not. (@smarter)
  - [x] Additionally if so, decide if simple enum constants become `case object` not `val`.
- [x] crash with java enum and varargs: #7734
- [x] implement precise return type on `.apply` for companion objects of class enum cases, and widen the class to the base enum when inferring types.
- [x] drop `enumLabel`
- [x] keep values array and valueOf only when singleton values appear
- [x] make `$fromOrdinal` companion method public and rename to `fromOrdinal`

**Comment by nicolasstucki** [comment]
Discussion should go in individual issues.

**Comment by odersky** [comment]
> Additionally if so, decide if simple enum constants become case object not val.

They should definitely stay vals. case objects generate way too much bytecode. The point of simple enum constants is that you can have hundreds of them in a type. I don't want a bloated jar because of that.

**Comment by abgruszecki** [comment]
@bishabosha do you think we can close this?

**Comment by bishabosha** [comment]
yes I think so
