### ISSUE TITLE
TASTy as a Standard for Scala

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#8118]
This is a meta issue to collect issues regarding TASTy becoming a standard reference for the semantics of Scala, and removal of `dotc` implementation details from its binary representation.

- [ ] compiler internal types/symbols appearing in TASTy
  - [ ] `scala.&` and `scala.|` #7688 
  - [ ] `method java.lang.Enum.<init>`: `()java.lang.Enum` #7478
